### ISSUE TITLE
Unable to connect to deluge using a thin client

### ISSUE THREAD

**Issue by hoshinohikari** [linuxserver/docker-deluge#100]
## Expected Behavior
I tried using Transdrone to connect to deluge.

## Current Behavior
I used webui to turn on the allow_remote option.But I can't connect to deluge using another thin client, but the webui works fine and I can also access it from another webui on another server.

## Environment
**OS:Debian Sid
**CPU architecture:arm64
**How docker service was installed:**
official docker repo

## Command used to create docker container (run/create/compose/screenshot)
version: '3.3'
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=error
    volumes:
      - ./config:/config
      - /home/hoshino/Downloads:/downloads
    restart: unless-stopped

## Docker logs
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by j0nnymoe** [comment]
Make sure your deluge version's match between the version in the container and the version of the desktop client you're running.

**Comment by hoshinohikari** [comment]
I've used Android Transdrone, the deluge 2.0 client for Windows, and flexget all fail to connect.

**Comment by Drugantibus** [comment]
Same here! Enabled allow_remote both in `core.conf` and in WebUI, my Deluge server reports version `2.0.3-2-201906121747-ubuntu18.04.1` and the Windows client is just `2.0.3` (unofficial Drive installer)

**Comment by Drugantibus** [comment]
I actually just managed to get it to work. I only stopped the container, added a user in `auth`, and opened `core.conf` to check that `allow_remote` was enabled, but didn't make any changes. After restarting the container, I am able to login with both the user I just added and the `localclient` user.

**Comment by hoshinohikari** [comment]
> I actually just managed to get it to work. I only stopped the container, added a user in `auth`, and opened `core.conf` to check that `allow_remote` was enabled, but didn't make any changes. After restarting the container, I am able to login with both the user I just added and the `localclient` user. Also confirmed on Transdrone, using server "Deluge 1.2+".

In fact, deluge 1.2+ is based on a webui connection, which still doesn't work with Windows thin clients.

**Comment by hugalafutro** [comment]
Same issue here, everything works perfectly in webui, unable to connect with thin client on W10 x64 with the same login information. No output is made in the container logs.

**Comment by NeoMod** [comment]
Just my "+1" here...same situation as above: Winndows thin client (v. 1.3.15 since v2 is still not available) won't connect to Daeluge Daemon. (even though the rest of the configuration is correct and the webui is working)

**Comment by j0nnymoe** [comment]
You need to match the versions of the thin client and deluge itself.
Solution: https://github.com/linuxserver/docker-deluge/issues/100#issuecomment-731562748

**Comment by NeoMod** [comment]
Thank you @j0nnymoe 
I did understand the problem, I wrote just to specify (and help other users with potentially the same issue). Since V2 of Deluge Client is not available for Windows there is nothing the user, nor the maintainer of the container, can do.

**Comment by NeoMod** [comment]
Users who _**absolutely need**_ a working **Deluge Thinclient** on a **Windows** machine at the moment have one possible solution: using an **unofficial installer compiled and maintained by Deluge Users** and available on Deluge Forum.

The **latest installer**, compiled by user _"mherz"_, is **available here:** [link](https://forum.deluge-torrent.org/viewtopic.php?p=233581#p233581)

**Please do read the [info at the beginning of the thread](https://forum.deluge-torrent.org/viewtopic.php?p=232351#p232351)** to learn _what and what-not_ about this version.

I believe that **this should be pointed out as a "solution"** _- albeit partial, temporary and with the clear indication of unofficiality -_ for Windows Users looking for a Thinclient for Deluge 2.
