### ISSUE TITLE
Unable to login to Web UI

### ISSUE THREAD

**Issue by vascozorrinho** [linuxserver/docker-deluge#104]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I've noticed that i can't access the web UI. The password is not accepted even though it's saved in the browser. I've been doing some torrent cleanup the day before and everything was ok.

## Current Behavior
When I access the Web UI, I get the login login popup but the saved password is not accepted.

## Steps to Reproduce

1. Access web ui
2. click "login"

## Environment
**OS:** Raspbian OS with December update 
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
Standard DockSTARTer instalation
**NOTE**: tried before and after applying this solution [My host is incompatible with images based on Ubuntu Focal](https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal)

## Command used to create docker container (run/create/compose/screenshot)
Standard DockSTARTer instalation

## Docker logs
21:50:44 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:50:45 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:50:56 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:50:56 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:50:57 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
		 
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
21:52:40 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
21:53:06 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:08 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:17 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:17 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:36 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:42 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:43 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:44 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:45 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:52 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:53:55 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:54:12 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:54:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:54:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:54:29 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:54:49 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:55:10 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:55:11 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:55:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 192.168.100.10)
21:55:33 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:55:45 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:55:45 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:56:01 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:56:11 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:56:31 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:57:03 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:57:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:57:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:57:35 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:58:07 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:58:39 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:58:45 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:58:45 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:58:59 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 192.168.100.10)
21:59:07 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:59:11 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
21:59:38 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:00:10 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:00:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:00:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:00:42 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:01:14 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:01:46 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:02:18 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:02:50 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)
22:03:05 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.18.0.1)

**Comment by katacarbix** [comment]
I'm also having this issue. I've tried setting the `PASSWORD` environment variable and still no luck. I may try using a password file next.

**Comment by katacarbix** [comment]
Actually I think I figured out what's happening but I don't know how to fix it.

I believe the default password is "deluge", because when I enter that, a box titled "Change default password" pops up but immediate after another login box pops up on top of it so I can't interact with it. I also don't get an incorrect password warning when I use that.

On page load I get these warnings in the javascript console:

```
> This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 192.168.0.28:8112
> Some cookies are misusing the recommended “SameSite“ attribute (3)
> Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. {Learn More]
```

(I'm accessing it over the local network and it is not exposed to the internet, so HTTPS is not necessary.)

Then when I enter "deluge" I get this warning:

```
> Cookie “_session_id” has been rejected because it is already expired.
```

So it seems like a cookie error.

**Comment by katacarbix** [comment]
I fixed it, it turns out my system time was wrong; it's a new computer with a fresh Arch install and I forgot to configure `ntpd`. 🤦

**Comment by havrancek** [comment]
I have such problem now.
I cant log into deluge in docker on synology nas.
23:19:40 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.17.0.1)
this is all I get
