### ISSUE TITLE
Allow custom internal download path to avoid difficulties with NAS systems

### ISSUE THREAD

**Issue by alxpettit** [linuxserver/docker-deluge#114]
## Desired Behavior
Allow customizing the download path created in container

## Current Behavior
Path is hardcoded to /downloads

## Alternatives Considered
It is possible to simply use `/downloads`, but it doesn't fit all use cases. For instance, if you're using Deluge with a client-server model -- having the GTK client on your laptop, and the docker server on your desktop -- you may want to have a specific path that are identical on both the client and the server.

I for instance like to have a sshfs-mounted directory called `/nas0` with a meticulously organized set of file paths for various purposes -- one of which is `/nas0/torrents`. But if I try to bind `/downloads` to `/nas0/torrents` as things are, it ends up with the wrong permissions and I get constant `Permission denied` errors on my torrents. Meanwhile, if I set the path to `/downloads` internally, I no longer get the feature where if you double click on a file in the GTK interface, it pops open the corresponding path in the file manager.

To have a smooth NAS architecture, it is very useful to have identical custom paths for this use case.

**Comment by aptalca** [comment]
You can map any folder any way you like. The only required internal folder mapping you can't change is `/config`

**Comment by alxpettit** [comment]
I tried, though. I got `Permission denied`, and when I changed the internal path back to `/downloads`, it worked.

**Comment by aptalca** [comment]
You need to make sure permissions are correct

**Comment by alxpettit** [comment]
I did. I created a user with a specific UID/GID and set them accordingly in my `docker-compose.yml`. I chowned/chmodded all files in the directory appropriately, and double checked them multiple times. The one variable that made it work, was switching back to using `/downloads`.

**Comment by alxpettit** [comment]
My guess is that the mountpoint in the container needs its permissions set appropriately too. I've noticed that you have [a file that seems to confirm this](https://github.com/linuxserver/docker-deluge/blob/master/root/etc/cont-init.d/30-config).

**Comment by alxpettit** [comment]
[This](https://github.com/alxpettit/docker-deluge/blob/master/root/etc/cont-init.d/30-config) seems to work.

**Comment by alxpettit** [comment]
Turns out it was an issue with the `volumes` support on my docker instance. Updating fixed it. :woman_shrugging:

**Comment by alxpettit** [comment]
Still not sure why the `chmod` command exists in that file, and is hardcoded to `/downloads`. If it's not needed, it should probably be removed from the script.
