### ISSUE TITLE
Humble request to make deluge mobile friendly

### ISSUE THREAD

**Issue by emkowale** [linuxserver/docker-deluge#116]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Desired Behavior
As a techy guy it love to keep my eye on how my stuff is doing. I vpn into my network via smartphone and it would be EPIC if deluge was mobile friendly.

## Current Behavior
Very difficult to use on the phone. In fact, I am unable to "force recheck" because there is no way to right click on a phone.

## Alternatives Considered
I have to just use the desktop version.

**Comment by Roxedus** [comment]
We do not create Deluge itself, this is a request suited for them.
