### ISSUE TITLE
Deluge resets webui password on restart

### ISSUE THREAD

**Issue by totopesce** [linuxserver/docker-deluge#119]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Webui password should remain after restarts.

## Current Behavior

Webui password resets to deluge after restarts.

## Steps to Reproduce

1. Change webui password
2. Restart docker
3. Password resets to deluge

## Environment
**OS: Openmedia Vault 4
**CPU architecture:** x86_64
**How docker service was installed:

Through Omvs docker installer.

## Command used to create docker container (run/create/compose/screenshot)

With Omvs docker install, restart always, puid and pgid, timezone and volumes.

## Docker logs

`
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO    ] 00:52:04 configmanager:70 Setting config directory to: /config
[INFO    ] 00:52:04 ui:124 Deluge ui 1.3.15
[INFO    ] 00:52:04 ui:127 Starting web ui..
[INFO    ] 00:52:05 server:666 Starting server in PID 235.
[INFO    ] 00:52:05 server:679 Serving on 0.0.0.0:8112 view at http://0.0.0.0:8112
[ERROR   ] 00:52:38 auth:330 Login failed (ClientIP 192.168.0.151)
[INFO    ] 00:52:46 auth:327 Login success (ClientIP 192.168.0.151)
[INFO    ] 00:52:48 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 00:52:48 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 00:52:48 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 00:52:48 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 00:52:48 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection was closed cleanly.
[INFO    ] 00:52:48 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection was closed cleanly.
[INFO    ] 00:52:50 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 00:52:50 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 00:52:50 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection was closed cleanly.
[INFO    ] 00:52:51 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 00:52:51 client:121 Connected to daemon at 127.0.0.1:58846..
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:1243: UserWarning: /config/plugins/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
[INFO    ] 00:52:51 pluginmanagerbase:158 Plugin AutoRemovePlus enabled..
[INFO    ] 00:52:51 pluginmanager:108 'WebUi' plugin contains no WebUI code, ignoring WebUI enable call.
[INFO    ] 00:52:51 pluginmanager:108 'YaRSS2' plugin contains no WebUI code, ignoring WebUI enable call.
[INFO    ] 00:52:51 pluginmanagerbase:158 Plugin Label enabled..`

**Comment by thelamer** [comment]
You have to logout of the webUI.
