### ISSUE TITLE
Deluge on Docker creating some conf files using wrong privileges

### ISSUE THREAD

**Issue by TheBR** [linuxserver/docker-deluge#123]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

web.conf and label.conf should be created with the correct privileges of owner:group - umask

## Current Behavior

web.conf and label.conf (as well as .bak files) are created with rw for owner only.

## Steps to Reproduce

1. Install Deluge in docker with someuser:everyone
2. When deployed log into console for container
3. ls -al in /config directory
4. web.conf and label.conf will be rw for owner only, all other files are ok.

## Environment
**OS:**
QNAP NAS
**CPU architecture:** x86_64/arm32/arm64 
x86_64
**How docker service was installed:**

NAS OS Provided

## Command used to create docker container (run/create/compose/screenshot)

Image:
linuxserver/deluge:latest 
ENV Variables
https://imgur.com/a/GisbbI0

## Docker logs

[~] # docker logs 8bf96c506590
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1002
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
09:55:00 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'

root@Deluge:/config# ls -al
total 184
drwxrwxr-- 9 abc  users  4096 Aug 16 09:55 .
drwxr-xr-x 1 root root   4096 Aug 16 09:54 ..
drwxrwxr-- 2 abc  users  4096 Feb  5  2021 archive
-rwxrwxr-- 1 abc  users    56 Dec  1  2020 auth
-rwxrwxr-- 1 abc  users   454 Jun 21 09:28 autoremoveplus.conf
-rwxrwxr-- 1 abc  users   451 Feb  3  2021 autoremoveplus.conf.bak
-rwxrwxr-- 1 abc  users    36 Dec 14  2020 autoremoveplusstates.conf
-rwxrwxr-- 1 abc  users  2804 Apr 29 07:32 core.conf
-rwxrwxr-- 1 abc  users  2803 Dec 26  2020 core.conf.bak
drwxrwxr-- 2 root root   4096 Jun 17 04:00 custom-cont-init.d
drwxrwxr-- 2 root root   4096 Jun 17 04:00 custom-services.d
-rwxrwxr-- 1 abc  users  2719 Aug 16 12:13 deluged.log
-rw-r--r-- 1 abc  users    10 Aug 16 09:55 deluged.pid
-rwxrwxr-- 1 abc  users   252 Dec  1  2020 hostlist.conf
drwxrwxr-- 2 abc  users  4096 Dec  1  2020 icons
**-rw------- 1 abc  users  2163 Aug 15 10:28 label.conf
-rw------- 1 abc  users  2488 Aug 13 15:50 label.conf.bak**
drwxrwxr-- 3 abc  users  4096 Feb  5  2021 plugins
-rw-r--r-- 1 abc  users  4443 Aug 16 09:54 session.state
-rw-r--r-- 1 abc  users  5507 Aug 16 09:24 session.state.bak
drwxrwxr-- 2 abc  users  4096 Dec  1  2020 ssl
drwxrwxr-- 2 abc  users  4096 Aug 16 16:24 state
**-rw------- 1 abc  users 44883 Aug 16 09:54 web.conf
-rw------- 1 abc  users 44163 Aug 16 09:24 web.conf.bak**
[~] # umask
0022

**Comment by thelamer** [comment]
These are the default permissions set by the application.
