### ISSUE TITLE
Add container variable "shared"

### ISSUE THREAD

**Issue by lucidnx** [linuxserver/docker-deluge#125]
Currently deluge2 supports multi-user downloads (separated quenes for each user). There is option in core.conf to set all torrents as shared between these users.
config line:
` "shared": true,`

Please add this option to container vars :)

**Comment by drizuid** [comment]
PRs are welcome, please thoroughly test!

**Comment by thelamer** [comment]
We will not be implementing this, you can customize your configuration after the fact. Setting this via the console is not difficult: 
```
readarray -d : -t auth < <(cat /config/auth)
deluge-console -U ${auth[0]} -P ${auth[1]} config --set shared true
```
