### ISSUE TITLE
Add ability to run Ping inside container

### ISSUE THREAD

**Issue by MCTyler** [linuxserver/docker-deluge#128]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
<--- Health Check, ability to Ping Google inside container -->

## Current Behavior
<--- Log reports Ping command not found -->

## Alternatives Considered
<--- Run without Health check -->

**Comment by j0nnymoe** [comment]
You can add ping by using this mod https://github.com/linuxserver/docker-mods/tree/universal-tshoot
