### ISSUE TITLE
Deluge-console "password does not match"

### ISSUE THREAD

**Issue by Matszwe02** [linuxserver/docker-deluge#132]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I tried to login with deluge-console, but default credentials don't work
------------------------------

## Expected Behavior

include password in readme or change it to default "deluge"

## Current Behavior

webGUI works ok, only deluge-console doesn't work

## Steps to Reproduce

1. deluge-console connect 127.0.0.1:58846
2.it should automatically connect with user: localclient password: deluge
![image](https://user-images.githubusercontent.com/49353902/149763124-ad9b0b4f-4c19-4c16-b3b3-cef6d0f4677a.png)

## Environment
**OS:**
**CPU architecture:** x86_64  and  arm64
**How docker service was installed:**

linux on RPI and windows

## Command used to create docker container (run/create/compose/screenshot)

default docker-compose file

**Comment by thelamer** [comment]
This is not how deluge console works, the auth for deluge-console is included in /config/auth

**Comment by Khopylium** [comment]
Did somebody found a fix or a workaround ?

**Comment by jaqarrick** [comment]
I'm also experiencing this issue and have yet to find a solution. @thelamer Yes, the auth is in `~/.config/auth` which looks like this:
```
localclient:mypassword:10
```
Tried

`deluge-console  "-U localclient -P mypassword connect 127.0.0.1:58846"`
and 
`deluge-console connect 127.0.0.1:58846`

Both have the same error:
```
Could not connect to daemon: 127.0.0.1:58846
 Password does not match
```

**Comment by dimkasta** [comment]
This still fails with the same error. the web ui works ok

**Comment by ssj4maiko** [comment]
OK, I have found a way to fix this, but it would be nice if this could be automated.

First access `bash`:
```
docker compose exec deluge bash
```
Now inside the container you do this:
```
cat /root/.config/deluge/auth
```
There will be a line there, copy it.

Now outside of the container, in your config folder (supposing it's `./config`:
```
nano .config/auth
```
copy the line into the first line, and remove the original. You can now access deluged-console without the password error.

**Comment by rybkin** [comment]
I was able to launch it just using `deluge-console -c /config/`
