### ISSUE TITLE
OS change

### ISSUE THREAD

**Issue by dmzoneill** [linuxserver/docker-deluge#136]
Consider that changing the OS from deb/ubuntu to arch has breaking changes for subscribers :)

**Comment by thelamer** [comment]
This is heavily considered when rebasing an image. The change from Ubuntu to Alpine will break user's customization if leveraging os tools to install additional packages, also the bump in Python considered for plugin integration as some eggs require specific versions. 
These changes were made to automate initial configuration, have upstream package support, fix a backlog of issues including incompatible default plugins, missing geo data, older libtorrent among others. 
Our goal is to serve the majority of users, when spinning up a new image or using this image normally, the recent change greatly improves that experience. If you are a power user with many customizations you basically have two options to rip the band aid off and continue using this image for update by updating any user customization/plugins, or fork the code and use an older/alternative image. 
Please use github to report a bug or request a feature, we have other support channels for overarching discussion: 
https://discourse.linuxserver.io/
https://discord.gg/YWrKVTn
