### ISSUE TITLE
deluged run script is missing UMASK

### ISSUE THREAD

**Issue by nettucu** [linuxserver/docker-deluge#147]
Latest versions of the root/etc/services.d/deluged/run no longer sets the UMASK; unlike previous versions.
Now the image no longer sets the UMASK even though the env param is set in the docker file.

**Comment by Roxedus** [comment]
This is a know issue, and will be fixed on the next build, as that has the fixed base image.

**Comment by Panderine** [comment]
Hi!, any ETA for next build? this issue is halting all my automation :(

**Comment by putnam** [comment]
This is breaking everything for me too. Seems like a major bug, maybe hotfix?

**Comment by Panderine** [comment]
Sorry, I'm still having this issue even with alpine 3.16 rebase release.

**Comment by thespad** [comment]
Is this still an issue? Should be fixed across the board at this point.

**Comment by thespad** [comment]
Going to need someone to follow the issue template and actually provide some environmental details + logs/evidence to demonstrate the issue because I can't replicate it.
