### ISSUE TITLE
Release new Deluge version

### ISSUE THREAD

**Issue by frnjjq** [linuxserver/docker-deluge#151]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Currently Deluge has released the new version 2.1.0.

https://deluge.readthedocs.io/en/latest/changelog.html

Last versions available as Linusserver.io build is 2.0.5. I would consider to release a new version contaning the latest Deluge version.

**Comment by Roxedus** [comment]
We push the latest version available in the alpine package repo. You would need to as them to update the version they push.

**Comment by alpe12** [comment]
Wouldn't it be possible to make a branch that builds it from source?

**Comment by alpe12** [comment]
Or better yet. A branch that uses the Edge branch of alpine. It is 2.1.1 there.

**Comment by chouex** [comment]
just change 1 line in package_versions.txt @2.0.5-r1-ls164
```
-deluge-2.0.5-r1
+deluge-2.1.1-r0
```
and build it 
```
docker build               --label "org.opencontainers.image.created="               --label "org.opencontainers.image.authors=linuxserver.io"               --label "org.opencontainers.image.url=https://github.com/linuxserver/docker-deluge/packages"               --label "org.opencontainers.image.documentation=https://docs.linuxserver.io/images/docker-deluge"               --label "org.opencontainers.image.source=https://github.com/linuxserver/docker-deluge"               --label "org.opencontainers.image.version=-ls"               --label "org.opencontainers.image.revision="               --label "org.opencontainers.image.vendor=linuxserver.io"               --label "org.opencontainers.image.licenses=GPL-3.0-only"               --label "org.opencontainers.image.ref.name="               --label "org.opencontainers.image.title=Deluge"               --label "org.opencontainers.image.description=[Deluge](http://deluge-torrent.org/) is a lightweight, Free Software, cross-platform BitTorrent client.    * Full Encryption  * WebUI  * Plugin System  * Much more...  "               --no-cache --pull -t chou/deluge:amd64-2.1.1  ```

**Comment by Roxedus** [comment]
> just change 1 line in package_versions.txt @2.0.5-r1-ls164
> 
> ```
> -deluge-2.0.5-r1
> +deluge-2.1.1-r0
> ```
> 
> and build it
> 
> ```
> docker build               --label "org.opencontainers.image.created="               --label "org.opencontainers.image.authors=linuxserver.io"               --label "org.opencontainers.image.url=https://github.com/linuxserver/docker-deluge/packages"               --label "org.opencontainers.image.documentation=https://docs.linuxserver.io/images/docker-deluge"               --label "org.opencontainers.image.source=https://github.com/linuxserver/docker-deluge"               --label "org.opencontainers.image.version=-ls"               --label "org.opencontainers.image.revision="               --label "org.opencontainers.image.vendor=linuxserver.io"               --label "org.opencontainers.image.licenses=GPL-3.0-only"               --label "org.opencontainers.image.ref.name="               --label "org.opencontainers.image.title=Deluge"               --label "org.opencontainers.image.description=[Deluge](http://deluge-torrent.org/) is a lightweight, Free Software, cross-platform BitTorrent client.    * Full Encryption  * WebUI  * Plugin System  * Much more...  "               --no-cache --pull -t chou/deluge:amd64-2.1.1  ```
> ```

This is not how that file works, it's just a output file, not input.

**Comment by physk** [comment]
Quick and dirty way of getting 2.1.1 still using linuxserver.io

Create folder and change to the directory

```bash
cd ~ && mkdir -p Docker/deluge && cd ~/Docker/deluge
```

Create Dockerfile
```bash
touch Dockerfile && \
cat <<EOF > Dockerfile
FROM lscr.io/linuxserver/deluge:latest

RUN echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && apk add --no-cache deluge@edge
EOF
```

Build Docker Image
```
docker build -t deluge:latest .
```

Use ``deluge:latest`` as your image when creating docker container
