### ISSUE TITLE
Update Deluge to version 2.1.1

### ISSUE THREAD

**Issue by IvanDrag0** [linuxserver/docker-deluge#153]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Update Deluge to version 2.1.1. Version 2.1 introduced a significant number of changes and bug fixes.

## Current Behavior
Current Deluge version is 2.0.5, which is dated 2021-12-15.

**Comment by j0nnymoe** [comment]
Dupe and reason already explained here https://github.com/linuxserver/docker-deluge/issues/151

**Comment by ngosang** [comment]
@Roxedus @j0nnymoe it's unlikely they update deluge until Alpine 3.17. You were using edge branch until recently => https://github.com/linuxserver/docker-deluge/pull/146
