### ISSUE TITLE
Publish Deluge 2.1.1

### ISSUE THREAD

**Issue by ngosang** [linuxserver/docker-deluge#154]
Latest release from LinuxServer is 2.0.5 but 2.1.1 is out.
Take a look at the changelog => https://deluge.readthedocs.io/en/latest/changelog.html

Breaking changes

    Python 2 support removed (Python >= 3.6)

    libtorrent minimum requirement increased (>= 1.2).

**Comment by Roxedus** [comment]
Dupe of #153
