### ISSUE TITLE
Loglevel not registering

### ISSUE THREAD

**Issue by Subbeh** [linuxserver/docker-deluge#156]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Log level should be changed based on the DELUGE_LOG_LEVEL environment variable

## Current Behavior
Log level is not changed

## Steps to Reproduce
1. Run docker container with DELUGE_LOGLEVEL set to debug
2. Verify in container by checking the environment variables:
```
# echo $DELUGE_LOG_LEVEL
debug
```
3. Verify command line options:
```
# ps -eaf|grep deluged
abc          133     129  1 12:04 ?        00:00:02 /usr/bin/python3 /usr/bin/deluged -c /config -d --loglevel=info
```
4. Loglevel is still set to info

## Environment
**OS:** docker
**CPU architecture:** x86_64
**How docker service was installed:**
lscr.io/linuxserver/deluge:latest

**Comment by scot-t** [comment]
The correct env var should be `DELUGE_LOGLEVEL`, your example has an additional underscore.

**Comment by Subbeh** [comment]
Facepalm.. thanks @scot-t
