### ISSUE TITLE
v2.0.5 is two versions behind current v2.1.1

### ISSUE THREAD

**Issue by nopoz** [linuxserver/docker-deluge#157]
the linuxserver docker container is on 2.0.5 while the deluge release changelog shows two newer versions, 2.1.0 and 2.1.1

changelog can be found here: https://deluge.readthedocs.io/en/latest/changelog.html

**Comment by j0nnymoe** [comment]
Dupe https://github.com/linuxserver/docker-deluge/issues/153 & https://github.com/linuxserver/docker-deluge/issues/154

**Comment by nopoz** [comment]
For reference, I found a solution for upgrading to 2.1.1 in this comment from https://github.com/linuxserver/docker-deluge/issues/151#issuecomment-1215976556
