### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by gpapin** [linuxserver/docker-deluge#16]
I was getting this error when using the YARSS2 plugin:
```ozo_exception when parsing rssfeed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>```

I had to run this in the container context to fix it:
```apk add --update ca-certificates openssl && update-ca-certificates```

It would be good to add that to the dockerimage so it won't happen to anyone else

**Comment by sparklyballs** [comment]
openssl is deprecated in alpine in favour of libressl, can you test this on a fresh pull of the image please (so you don't have openssl package still installed.

`apk add --no-cache ca-certificates libressl && update-ca-certificates`

**Comment by gpapin** [comment]
@sparklyballs here is the output : 
```
root@3ca11ab906e5:/$ apk add --no-cache ca-certificates libressl && update-ca-certificates
fetch http://alpine.gliderlabs.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libressl (missing):
    required by: world[libressl]
```

**Comment by sparklyballs** [comment]
my bad, i'm working on an edge baseimage of deluge...

`apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/main libressl`
`apk add --no-cache ca-certificates`
and then the update

**Comment by gpapin** [comment]
Ok so here is the trace:

```
root@3ca11ab906e5:/$ apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/main libressl
fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/1) Installing libressl (2.4.4-r0)
Executing busybox-1.24.2-r11.trigger
OK: 167 MiB in 110 packages

root@3ca11ab906e5:/$ apk add --no-cache ca-certificates
fetch http://alpine.gliderlabs.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20160104-r4)
Executing busybox-1.24.2-r11.trigger
Executing ca-certificates-20160104-r4.trigger
OK: 167 MiB in 111 packages

root@3ca11ab906e5:/$ update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
```

**Comment by sparklyballs** [comment]
yeah, that last message is nothing to worry about.

**Comment by gpapin** [comment]
cool :)

**Comment by sparklyballs** [comment]
does the plugin work with libressl ?

i'm rebasing the image to an edge baseimage so it build properly, as part of that i can add libressl and ca-certificates to the runtime packages if they work with yar.......

**Comment by gpapin** [comment]
Well it's hard to say as I have only one rss and it has nothing new so it won't pull anything just yet.
But a wget of that url that didn't work now works fine with the patch.

I'll give you more feedback when the RSS will be updated - but I think it should be good.

**Comment by gpapin** [comment]
Ok I can confirm that the yarss2 plugin works now. good job

**Comment by gpapin** [comment]
I have the exact same issue again :( ...
This time the commands above don't solve the issue, any ideas ?

**Comment by gpapin** [comment]
Just a heads up, I was running on the latest deluge image but I had to run the command above again to get it working again after updating.

**Comment by davida72** [comment]
Old thread, but i'm seeing the same problem. Additionally, my Deluge Docker doesn't seem to have APK so I can't update the certificates, unless I'm missing something? Help appreciated.

**Comment by silkyclouds** [comment]
Hi gents,

I ran all the above commands but still end up with the certificate verification issue. 

the exact same feed do work in rtorrent rss manager. So is there anything you guy can do to fix this on your end ?

**Comment by barart** [comment]
@gpapin How do you install the plugin? Im trying to install it but it just do nothing (no errors, no confirmations)
