### ISSUE TITLE
deluge web ui fails to load

### ISSUE THREAD

**Issue by Tumtum2814** [linuxserver/docker-deluge#163]
I have deluge deployed on a debian machine via docker compose. It was working fine and all of the sudden started crashing and then never came back up. I have tried removing the container, removing the config files from the drive, rolling back to a previous version. When i log into the container, the mounts show up and the container is running but i just get connection refused on the webui. Also i turned on error logging but it doesn't look like it's logging?

`version: "3.4"
services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge:version-2.1.1-r1 #linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: host # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${WIN}/torrents:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp`

`[custom-init] No custom services found, skipping...

[migrations] started

[migrations] no migrations found

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    1001

User gid:    1001

-------------------------------------

      
      `

**Comment by andywong36** [comment]
I'm having similar problems. Have you found a fix yet?

**Comment by Tumtum2814** [comment]
My core.conf was corrupt. I deleted it and re-setup deluge and I'm back up
and running. Not ideal but at least it's up again.
