### ISSUE TITLE
GeoIP flags no longer display

### ISSUE THREAD

**Issue by dj3520-git** [linuxserver/docker-deluge#168]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
GeoIP flags should appear next to IP addresses of connected seeds/peers. This has actually been broken for some time, many container updates have occurred since noticing the issue.

## Current Behavior
GeoIP flags do not display...

I've done a little bit of digging and the issue seems to be the IP database is no longer hosted at the URL the Dockerfile uses to fetch it during the image build. URL below:
https://ipfs.infura.io/ipfs/QmWTWcPRRbADZcLcJeANZmcJZNrcpmuQgKYBi6hGdddtC6

When the image is created, the message on the webpage (Domain ipfs.infura.io isn't active anymore. Use infura-ipfs.io) becomes the contents of GeoIP.dat inside the container. I didn't have much luck with the new domain in the message though.

What I did find is this, and I have successfully downloaded the 'DB-IP - Country IPv4' version from the below site and copied the extracted database into a running container:
https://www.miyuru.lk/geoiplegacy 

After re-applying the GeoIP.dat file in Deluge's settings the GeoIP flags are back!

This is what I've been doing from the docker host after a container update to get the flags back:
`curl -L "https://dl.miyuru.lk/geoip/dbip/country/dbip4.dat.gz" -o /tmp/dbip4.dat.gz`
`gzip -d /tmp/dbip4.dat.gz`
`docker cp /tmp/dbip4.dat deluge:/usr/share/GeoIP/GeoIP.dat`
`rm -f /tmp/dbip4.dat`

## Steps to Reproduce

1. Spin up a Deluge container
2. Log into the WebUI or connect a thin client
3. Download/seed a torrent - connected seeds/peers will not have country flags next to their IP addresses

## Environment
**OS:** Debian 10
**CPU architecture:** x86_64
**How docker service was installed:** From the official docker repo, docker is the latest version.

## Command used to create docker container (run/create/compose/screenshot)

Docker compose used.

## Docker logs

N/A at this stage.

**Comment by prashker** [comment]
Put in a pull req to address this, the new URL they recommend seems to work, so I'm not sure why it didn't work for you.
Hopefully this gets sorted out!
