### ISSUE TITLE
[Solved ]Deluge doesn't save downloads to the mapped volume

### ISSUE THREAD

**Issue by Mahmoud87** [linuxserver/docker-deluge#17]
When i add a torrent to deluge and specify the shares, one for config and one for downloads. It downloads the data in a subfolder under the config share. I have changed the download share different times but doesn't work and totally ignores the specified download share and download the torrent data in the config share. I have made sure that UID and GUID am using having permissions to the download share.
	

Rockstor

**Comment by sparklyballs** [comment]
you have to change the /downloads location in the webui 

https://github.com/linuxserver/docker-deluge#setting-up-the-application

i use this container constantly and with the correct settings in the webui have never seen this.

**Comment by Mahmoud87** [comment]
I had to install it from fresh and recreated new shares made sure permissions are set correctly and all working perfectly fine now 👍 Thanks for your quick replay @sparklyballs I wanted to test everything before I reply. I will mark it as solved, thanks again.
