### ISSUE TITLE
[FEAT] Include YaRRS2 as a plugin

### ISSUE THREAD

**Issue by Maltavius** [linuxserver/docker-deluge#178]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please include the YaRRS2 plugin in this image.

### Reason for change

You are using a newer Python version than the ones  that are present on YaRSS2 site. It's a very popular RSS-client for Deluge and it need to be installed in both Server and Client to work.

### Proposed code change

No code

**Comment by dzhuang** [comment]
I've cooked one my self. 

    docker pull dzhuang/docker-deluge

The build code is in my repo https://github.com/dzhuang/deluge-alpine-build
