### ISSUE TITLE
PUID Not working Synology Docker Container

### ISSUE THREAD

**Issue by arette** [linuxserver/docker-deluge#18]
Using deluge docker container on a Synology 1515+ running the latest DSM.  I cannot get the PUID environment variable to work.  PUID comes up as 0 no matter what I specify as PUID in the docker container environment tab.  PGID appears to be working correctly. Thank you for your time!

**Comment by arette** [comment]
below is a snippet of the log on startup following a change to my PUID, not sure about the usermod error, so I just created a new user and fed it that ID instead (just in case the usermod error was the issue), but got the same behavior and same written to logs.


*** Running /etc/my_init.d/10_add_user_abc.sh...
usermod: user abc is currently used by process 1

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io

We do accept donations at:

https://www.linuxserver.io/donations

-------------------------------------

GID/UID

-------------------------------------

User uid:    0

User gid:    100

-------------------------------------

**Comment by sparklyballs** [comment]
need some screenshots of your setup page within synology for this docker, in particular sections relevant to this variable.

**Comment by arette** [comment]
![2016-12-23 08_06_31-nas-ette - synology diskstation](https://cloud.githubusercontent.com/assets/12751515/21454501/201050f0-c8e7-11e6-98bd-d4ca0b852ccd.png)

I should also note that I originally setup deluge with PUID and PGID = 0 (root) and (I thought) everything was working fine, but it turns out there is a slight permissions problem exporting my kodi library to the nfs share since everything downloaded by deluge ends up being owned by my synology root account.  That is why I am now, after using deluge docker for many months, am attempting to change my ids.  The key to my issue is answering/understanding why the usermod command is failing in the 10_add_user_abc.sh script in the linuxserver/docker-baseimage package...

**Comment by tobbenb** [comment]
The fact that you used root originally might be the reason for you problem.
I would start from scratch and do not use root.

**Comment by arette** [comment]
yeah, I was thinking of trying that but I have 500+ seeds for private trackers that I'm not sure how to maintain through that process.  Do you have any suggestions of how to start over but easily restore all my seeds in the fresh container?

**Comment by tobbenb** [comment]
Sorry, but I don't know deluge. 
You might be able to change the user:group of the /config folder through command line, but don't know how to do that on synology.

**Comment by arette** [comment]
For anyone reading this, I had success by "clearing" the container as shown in screenshot below.  Despite the warning about data loss, all of the container settings remained after clearing and restarting.  And, it then came up with the correct PUID (1024 in my case) and all torrents still seeding!  Thank you again for your support.
![2016-12-23 16_49_39-nas-ette - synology diskstation](https://cloud.githubusercontent.com/assets/12751515/21463072/10ef69f8-c932-11e6-8be5-ea8272bf7048.png)

**Comment by tobbenb** [comment]
Good you got it working. I consider the case closed ☺
