### ISSUE TITLE
[BUG] Docker compose failing on RPi4

### ISSUE THREAD

**Issue by brmdias** [linuxserver/docker-deluge#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker compose up is failing with this message:
[+] Running 0/1
 ⠙ deluge Pulling                                                                                                  5.1s
no matching manifest for linux/arm/v8 in the manifest list entries

The same compose.yml was working fine before. I just switched to a new SD Card and had to reinstall the OS.
OS is:
bruno@raspberrypi:~/smarthome/deluge $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Expected Behavior

Docker compose up should pull the container correctly

### Steps To Reproduce

1. with RPi4, Raspbian 11
2. with this compose file:
---
version: "2.1"
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /path:/config
      - /path:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
3. I'm getting this error after 'docker compose up'
[+] Running 0/1
 ⠙ deluge Pulling                                                                                                  5.1s
no matching manifest for linux/arm/v8 in the manifest list entries

### Environment

```markdown
- OS: Raspbian 11
- How docker service was installed: apt-get
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /path:/config
      - /path:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```

### Container logs

```bash
[+] Running 0/1
 ⠙ deluge Pulling                                                                                                  5.1s
no matching manifest for linux/arm/v8 in the manifest list entries
```

**Comment by j0nnymoe** [comment]
You have a arm/32bit OS installed. You need to reinstall a 64bit OS.
https://info.linuxserver.io/issues/2023-07-01-armhf/
