### ISSUE TITLE
[BUG] 2.1.1-r8-ls236 high CPU usage (using curl as health check)

### ISSUE THREAD

**Issue by Schmill** [linuxserver/docker-deluge#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CPU usage is extremely high, usually 50% (tying up one core), and then going to 100% when it takes the other core.

### Expected Behavior

CPU usages is normally very low.
Previously I was running 2.1.1-r8-ls231 and all was fine. I updated to the latest (242) and had this issue.
I then switch between various releases between them to find at what point the problem occurred. on 235 all is well, on 236 I get the issue.

### Steps To Reproduce

Installed the 236 image, and using curl for a health check.

### Environment

```markdown
OS: Synology DSM 6.1.7-15284 Update 3
Portainer running in a docker container.
Used Portainer "stack" to install the Deluge image.
```

### CPU architecture

x86-64

### Docker creation

```bash
deluge__nord_vpn:
  # #####################
  # Deluge (with NordVPN)
  # #####################
    container_name: deluge
    image: linuxserver/deluge:${DELUGE_VERSION}
    depends_on:
      vpn_nord:
        condition: service_healthy
    healthcheck:
      test: "curl -f --connect-timeout 120 ifconfig.io || exit 1"
      retries: 5
#      start_period: 2m
#    labels:
#      autoheal: "true"
    environment:
      - PUID=${USERID:?User Id not set}
      - PGID=${GROUPID:?User Id not set}
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /volume1/docker/deluge:/config
      - /volume1/downloads/:/downloads
    network_mode: "container:vpn_nord"
    restart: unless-stopped
    profiles:
      - nord_vpn

```
Environment variable "DELUGE_VERSION" set to either:
2.1.1-r8-ls235   - works
2.1.1-r8-ls236   - high cpu

### Container logs

```bash
ash-4.3# docker logs linuxserver.io
Error: No such container: linuxserver.io
ash-4.3# docker logs deluge
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1036
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
Connection to 127.0.0.1 58846 port [tcp/*] succeeded!
Connection to 127.0.0.1 8112 port [tcp/*] succeeded!
[ls.io-init] done.
```

**Comment by Schmill** [comment]
Using Portainer's "stats" view it seems to be the "curl" health check that is causing the high CPU usage:

![image](https://github.com/linuxserver/docker-deluge/assets/51209741/1ece02c8-c115-4905-b17b-2957b38c075a)

I am not sure why this would be though, since the health check operates without issue on 235...

**Comment by j0nnymoe** [comment]
Remove the health check, does it improve?

**Comment by Schmill** [comment]
Yes, if I disable the health check then I do not get high CPU usage with ls236, or if I leave the health check enabled but run ls235 then I do not get high CPU usage.
I am not sure what has changed in ls236 that would now cause the "curl" health check to be causing such high CPU usage.

**Comment by Schmill** [comment]
The issue still persists... I'm not sure how I keep this from going stale?

**Comment by thespad** [comment]
https://info.linuxserver.io/issues/2023-12-30-synology/

The underlying issue was fixed 3 weeks ago and there have been multiple Deluge builds since then which would include it.

**Comment by Schmill** [comment]
> https://info.linuxserver.io/issues/2023-12-30-synology/
> 
> The underlying issue was fixed 3 weeks ago and there have been multiple Deluge builds since then which would include it.

Oh excellent, many thanks for that. I thought that this ticket would get related to an issue if it was going to be worked on. I had no idea it had been done. Thanks!
