### ISSUE TITLE
Cannot connect to daemon within container

### ISSUE THREAD

**Issue by chpatton013** [linuxserver/docker-deluge#21]
## Brief

I cannot connect to the daemon within the running docker container. I have tried running `deluge-web` and `deluge-console` from within the container, as well as from the host system. In each case I was unable to connect to the daemon. I was able to connect to the daemon when I ran it directly on the host system.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]	

## More info

I have been using your image for several months with no problems. Today I was using the deluge web UI from the container to add a few small torrents. These torrents added successfully, and began downloading almost immediately. I switched tabs to my email and came back to the deluge tab about 30 minutes later. When I returned the connection manager was open, showing the daemon as `Offline`. The `Start Daemon` button had no effect. I was unable to click `Connect` from the web UI because the daemon was offline. I tried removing the daemon from the list so I could re-add it, but this also had no effect. I could not add a duplicate daemon to the connection manager.

Here is the output of `ps` from within the container:
```
root@feaf5c923037:/$ ps
PID   USER     TIME   COMMAND
    1 root       0:00 s6-svscan -t0 /var/run/s6/services
   33 root       0:00 s6-supervise s6-fdholderd
  205 root       0:00 s6-supervise deluged
  206 root       0:00 s6-supervise deluge-web
  208 abc        0:02 {deluge-web} /usr/bin/python /usr/bin/deluge-web -c /config --loglevel=info
  210 abc        0:00 {deluged} /usr/bin/python /usr/bin/deluged -c /config -d --loglevel=info -l /config/deluged.log
  269 root       0:00 /bin/bash
  321 root       0:00 ps
```

You can see that both processes are very much alive. I tried killing `deluged` with `SIGINT` so I could manually restart it and (hopefully) see more console output. `deluged` was restarted automatically for me, and I didn't deem it wise to delete the pid file and run multiple daemons. The `docker.log` file didn't offer much insight:
```
[INFO    ] 11:09:45 configmanager:70 Setting config directory to: /config
[INFO    ] 11:09:45 daemon:124 Deluge daemon 1.3.13
[INFO    ] 11:09:45 configmanager:70 Setting config directory to: /config
[INFO    ] 11:09:45 core:85 Starting libtorrent 1.0.9.0 session..
[INFO    ] 11:09:45 rpcserver:367 Starting DelugeRPC server :58846
[WARNING ] 11:09:45 preferencesmanager:496 Unable to find GeoIP database file!
[INFO    ] 11:09:45 torrentmanager:650 Successfully loaded state file: /config/state/torrents.state
[INFO    ] 11:09:45 torrentmanager:779 Successfully loaded fastresume file: /config/state/torrents.fastresume
```

I tried debugging this by running `deluge-console` from within the container and from the host system. I was not able to connect to the daemon from either instance of `deluge-console`. I then tried starting the web UI on my host system. I was unable to connect to the daemon from this instance as well. I found that I was able to successfully run (and connect to) the daemon if the daemon was run from the host system (using the same parameters I saw from `ps`, substituting volume mount paths). Everything seemed to work right away, which gives me some confidence that my config is not the problem. This isn't a great workaround though, since there are paths within the config that point to volume locations within the container.

I would like some assistance getting back to a working state. Let me know what information you need from me to help resolve this.

## Requested details

Host OS
```
%> uname -srvo
Linux 4.6.0-0.bpo.1-amd64 #1 SMP Debian 4.6.3-1~bpo8+1 (2016-07-13) GNU/Linux
```

Command line user
```
%> id
uid=1000(cpatton) gid=1000(cpatton) groups=1000(cpatton),24(cdrom),25(floppy),29(audio),30(dip),44(video),46(plugdev),108(netdev),115(bluetooth),999(docker)
```

Docker log
```
-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO    ] 10:46:21 configmanager:70 Setting config directory to: /config
[INFO    ] 10:46:21 ui:124 Deluge ui 1.3.13
[INFO    ] 10:46:21 ui:127 Starting web ui..
[INFO    ] 10:46:21 server:650 Starting server in PID 210.
[INFO    ] 10:46:21 server:664 serving on 0.0.0.0:8112 view at http://127.0.0.1:8112
[INFO    ] 10:46:21 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:21 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:21 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:21 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:26 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:26 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:26 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:26 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:28 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:28 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 server:681 Shutting down webserver
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

There are no symlinks within the volume mounts.

##  Thanks, team linuxserver.io

**Comment by eybox** [comment]
Bump on this thread, as I have a similar issue myself, that I would like to see resolved.

**Comment by gpborges** [comment]
Facing the exact same issue here. Web UI disconnecting after torrents starts downloading.

`[INFO    ] 00:43:36 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.`

**Comment by rg2k** [comment]
There is a simple fix:
1) Make sure "Allow Remote Connections" is enabled via the Web UI
2) Edit the auth file (~/config/deluge/auth) 
3) Add a username and password at the end of the file, i.e. deluge:deluge:10
4) Save the file
5) Restart the container
6) Configure the client to use the new username/password.

I tested this via the GUI client and Couchpotato and it works.

**Comment by gpborges** [comment]
I did the changes but still dropping the connection. :-(

1. "Allow Remote Connections" was not check by default and I did checked
(and confirmed).
2 and 3. My /config/deluge/auth file is like this (after adding the last
line as suggested):

localclient:6ea67cb40d6b235073657a6e9635d156d53fa5da:10
deluge:deluge:10

4 and 5. DONE
6. I'm connecting through the browser (FF).

If you have anything else I could try, I'd really appreciate.

Thanks.

Em ter, 9 de jan de 2018 às 14:48, rg2k <notifications@github.com> escreveu:

**Comment by soapy01** [comment]
hello,

This might be related so I ll just post this here.

I added deluge via docker and didn't not manage to connect to deluge daemon.
In the port settings I only saw that the daemon port 58846 was only there for UDP (or tcp can't remember) i added the other one and now it is working.

Note that for my issue, i could not connect AT ALL, so it wasn't a case of dropping the connection

**Comment by tobbenb** [comment]
@soapy01
We have specified it to run as host in the Readme. If you want to run it in bridge, you have have to figure out the ports yourself.

**Comment by teddybee** [comment]
I have the same issue as the above ones. I run it on a host net, but the daemon can't go online.
[INFO    ] 20:06:40 client:217 Connecting to daemon at 127.0.0.1:58846..
[WARNING ] 20:06:40 client:220 Connection to daemon at 127.0.0.1:58846 failed: Connection was refused by other side: 111: Connection refused.

**Comment by j0nnymoe** [comment]
@teddybee what's your docker run command?

**Comment by teddybee** [comment]
docker create \
  --restart=always \
  --name deluge \
  --net=host \
  -e PUID=114 -e PGID=118 \
  -e TZ=Europe/Berlin \
  -v /srv/dev-disk-by-id-ata-SAMSUNG-part6/srv/deluge/downloads/:/downloads \
  -v /srv/dev-disk-by-id-ata-SAMSUNG-part6/srv/deluge/config/:/config \
  -v /srv/dev-disk-by-id-ata-SAMSUNG-part6/srv/deluge/autoadd/:/autoadd \
  -v /srv/dev-disk-by-id-ata-SAMSUNG-part6/srv/deluge/completed/:/completed \
  linuxserver/deluge

**Comment by teddybee** [comment]
Probably the issue is connected to the OpenMediaVault 4. I can run the container without problem on another linux.

**Comment by jonatronnn** [comment]
Anyone found a solution for this? I can use the webui with no issue but cannot connect to the daemon via thin client on my local network.

**Comment by TheLostSwede** [comment]
I have exactly the same problem. Transdrone on my phone connects just fine, but then again, that connects via the web UI interface/port, not the daemon.

**Comment by jonatronnn** [comment]
@TheLostSwede So I've been able to get it to work, however I am not entirely sure what fixed it so I will run you through my entire setup:

I am running this container through dperson/openvpn-client for internet access. This container passes through the following ports for Deluge: 58846/tcp 58946/tcp 58946/udp 30895/tcp+udp (this is my open listen port as provided by my VPN provider). and 8112/tcp.

My docker run command is as follows:

sudo docker run -d --name=deluge --net=container:openvpn -e PUID=1001 -e PGID=1000 -e TZ=Europe/London -e UMASK_SET=022  -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/completed:/completed -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/autoadd:/autoadd -v /home/docker/.config/deluge:/config -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/completed-sonarr:/sonarr -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/completed-radarr:/radarr linuxserver/deluge:latest

Once Deluge is up and running you need to enable 'Allow Remote Connections' in the WebUI or in the config file.

I then added a user to the auth file in the config folder in the format: username:password:10

Then  load up your Deluge client, add the server as the local server IP and port 58846 then username and password as configured and it should work! 

Good luck!

**Comment by TheLostSwede** [comment]
The problem is that the thin client doesn't see the server in my case, despite it working via the web UI and Transdrone. Entering the IP address doesn't even give me an option to connect. And yes, I've enabled allow remote connections.

As I'm using OMV, most things were automagically configured for the docker. I tried bridging the IP addresses/ports, but that made zero difference.

**Comment by jonatronnn** [comment]
I am also using OMV4 and this is everything I did that managed to get it working.

I think the thing that solved it was adding the username and password to the auth and using those to connect rather than the default webui logon.

**Comment by krisvek** [comment]
Just wanted to confirm what jonatronnn said, adding username:password:10 to the auth file in the config folder is what solved this for me as well.

**Comment by TheLostSwede** [comment]
Right, so just getting the correct username and password format into the auto file solved it. What a silly issue and what a simple solution. Thanks for the help.

**Comment by TheLostSwede** [comment]
This is so frustrating, yesterday it was all working, but I had to re-install docker for various reasons and now I can no longer access the daemon, even though I used the same settings as yesterday. I have no idea why it's not working any more.

**Comment by thelamer** [comment]
Ok so two issues here , one is not running the container with host level networking one is for remote access which is solved by configuring the app. I am closing this old issue.

**Comment by ldexterldesign** [comment]
👋 https://github.com/linuxserver/docker-deluge/issues/86#issuecomment-586042444
