### ISSUE TITLE
Feature Request: Customize umask

### ISSUE THREAD

**Issue by demonspork** [linuxserver/docker-deluge#22]
Is there a way you could provide an environment variable or configuration option that would modify the `umask` that deluge will use when creating new files? The current `022` is problematic for my scenario because not all access to the filesystem will be done by the same user, but all access is restricted to the same group. I have 2 workarounds, 1 is manually editing `/etc/services.d/deluged/run` to change the `umask` to `002` or `007`, or using the execute plugin to perform the `chmod` to change the files to the necessary permissions, but I would rather be able to configure it in the container properties.

I am currently using this on unraid, but I think this would apply to all systems when using this docker container.

**Comment by sparklyballs** [comment]
there is no one size fits all setting for umask
execute plugin is how i modify permissions on downloads
