### ISSUE TITLE
Deluge erases Proxy settings set in core.conf or through web interfaces

### ISSUE THREAD

**Issue by ajthemacboy** [linuxserver/docker-deluge#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.10

`sudo docker create \
	--name deluge \
	-e VERSION=latest \
	-e PUID=1000 -e PGID=1000 \
	-e TZ="America/New_York" \
	-v /dock/deluge/downloads:/downloads \
	-v /dock/deluge/config:/config \
	-p 8112:8112 \
	--net docknet1 --ip 172.20.0.10 \
	linuxserver/deluge`

https://gist.github.com/ajthemacboy/b33ff11ac03e777c078760f30047943f

No symlinks

When I attempt to set proxy settings in the web interface, or copy working proxy settings from another Deluge installation's core.conf INTO the Deluge container's core.conf, all but the "Peer" proxy settings are removed.

Before: I fill out the proxy settings: http://eyestra.in/ul/u/FWVZpLk.png http://eyestra.in/ul/u/yyeDeoN.png

I click "Apply" or "OK", switch to another menu page, and return.  All but the "Peer" settings are removed: http://eyestra.in/ul/u/rcWGAVq.png

I also tried copying working proxy settings from the core.conf of another Deluge installation into the core.conf for the container. The proxy lines are replaced with empty lines: http://eyestra.in/ul/u/kg6Kik3.png

Whenever I set core.conf to be read-only with 0444, the lines remain in core.conf, but are empty in the web interface settings.

What I've tried:

- Removing the container and creating a new one
- Deleting the config folder and letting it regenerate
- Copying all the config files from another working installation into the container's config
- Made sure all file permissions are correct

**Comment by kmlucy** [comment]
It appears this is the correct behavior from Deluge, although it is very unclear: http://forum.deluge-torrent.org/viewtopic.php?f=12&t=54450&hilit=proxy

**Comment by ajthemacboy** [comment]
@kmlucy Thank you, that explains it.
