### ISSUE TITLE
Using bridge instead of host network

### ISSUE THREAD

**Issue by yehezkel** [linuxserver/docker-deluge#31]
This is more a question than an issue, what is the reason for to have as a requirement the host network?
i see the Dockerfile expose 4 ports, couldn't i just simply map each one of then? or use -P flag?

**Comment by n3mur1t0r** [comment]
You can use any network you want, I used this container with both bridge and macvlan networking with no issues.

**Comment by sparklyballs** [comment]
we don't recommend running as bridge but *you can* if you really want to

**Comment by ldexterldesign** [comment]
👋 https://github.com/linuxserver/docker-deluge/issues/86#issuecomment-586042444

**Comment by ipeacocks** [comment]
> We don't recommend running as bridge but you can if you really want to

But why?
