### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by evolution20** [linuxserver/docker-deluge#32]
I'm trying to set up Deluge in Docker on Synology DSM 6.1. I've set up the TZ, PGUID and PUID. 

![env](https://user-images.githubusercontent.com/32206800/30761329-bae7a658-9fd5-11e7-8b27-1b84223137f9.PNG)

The user has been specifically created for docker and is in the Admins group (ID 101), and the user ID is 1029.
Docker has been configured for the file paths: 

![volume](https://user-images.githubusercontent.com/32206800/30761540-83bc8bfc-9fd6-11e7-9e2b-c3ea6e5b071e.PNG)

Deluge has been configured as follows: 

![settings](https://user-images.githubusercontent.com/32206800/30761463-3d56cad8-9fd6-11e7-845c-12a55967b606.PNG)

And the error message I'm seeing is: 

![error](https://user-images.githubusercontent.com/32206800/30761468-442e08a8-9fd6-11e7-95a0-da9350328c8f.PNG)

**Comment by j0nnymoe** [comment]
@evolution20 remove the /NAS/ part of your locations, the application doesn't see that. You need to use `/downloads/incoming` & `/downloads/completed`

**Comment by evolution20** [comment]
Dammit! You're completely right! Thanks!
