### ISSUE TITLE
Update libtorrent libraries to latest versions

### ISSUE THREAD

**Issue by n1nj4888** [linuxserver/docker-deluge#34]
Can you please update the libtorrent libraries to the latest versions - the libraries in the container currently run 1.0.11 but the latest appears to be 1.1.6 and all the versions in between contain some important fixes, particularly around fixing proxy support...

https://github.com/arvidn/libtorrent/blob/master/ChangeLog

**Comment by n3mur1t0r** [comment]
The libtorrent version that comes with the container is the one in the Alpine Linux repositories, which is also the one that Deluge is working with. Deluge is incompatible with libtorrent 1.1, at least until Deluge 2.0 is released.

Even in the Ubuntu PPA maintained by the Deluge developer(s), libtorrent is still at 1.0.11: https://launchpad.net/~deluge-team/+archive/ubuntu/ppa

**Comment by sparklyballs** [comment]
@n3mur1t0r is correct
