### ISSUE TITLE
Default path for downloads within container is /root/Downloads

### ISSUE THREAD

**Issue by kurankat** [linuxserver/docker-deluge#37]
The default settings of the Deluge installation within the container specify `/root/Downloads` as the path for downloaded torrents, causing permission errors, and making the mounting of a volume in `/downloads` pointless.

Host OS: Ubuntu 16.04.3
Main user puid/guid = 1000/1000

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by sparklyballs** [comment]
you have to set /downloads as the default via the webui as per 

https://github.com/linuxserver/docker-deluge#setting-up-the-application

**Comment by zimmertr** [comment]
Hello @sparklyballs is it possible to define a different directory as the location for completed torrents?

If not, can a directory WITHIN that directory be defined as the location for completed torrents?

**Comment by magatst** [comment]
Same with me!
The github explanations do not solve anything.
A priori it would be a problem of authorization to write on the downloads folder!
But how do you solve it?
