### ISSUE TITLE
Allow Thin Client / add extra user

### ISSUE THREAD

**Issue by BoKKeR** [linuxserver/docker-deluge#38]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

#  Suggestion
http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient
It would be nice to have the thin client enabled by default or have a way to enable it easily. This allows clients to connect with the deluge program, not just the deluge web interface. There should be an option to add a user to the `/config/auth `file with 10 permission. for example` seedbox:deluge:10`
Additionally, the allow remote connections have to be enabled. this can be done with: 

`deluge-console "config -s allow_remote True"` 
` deluge-console "config allow_remote"` 

or left default off because it can be enabled from the web interface too.

 The ports that are already mapped should be enough for the thinclient.
# What you think your suggestion brings to the project, or fixes with the project
Enabled ThinClient. Adds extra user option.

**Comment by tobbenb** [comment]
If you can edit the auth file in /config and enable it through the web interface, you have your solution. Why open an issue for that?

**Comment by lvitti** [comment]
Editing the files doesn't work.
Can u explain how to do it ?
