### ISSUE TITLE
Synology LinuxServer/Deluge - Permission Denied

### ISSUE THREAD

**Issue by Niluan** [linuxserver/docker-deluge#41]
Hello Linuxserver.io and users.

I just downloaded Deluge image, and set it up in Docker, on my Synology DS1515+ with some of the other Docker images from LinuxServer, including Sonarr and CouchPotato. Which works just fine.
But i got some problems with the Deluge, when i'm trying to download something trough Deluge, i just got a "Permission Denied" error, every time i'm trying to download.

Sorry about the language, in my Synology setup, I'm from Denmark :)

<img width="820" alt="deluge1" src="https://user-images.githubusercontent.com/2924778/37206786-623ca30c-239a-11e8-9762-01e9eb7a1a07.PNG">
<img width="362" alt="deluge2" src="https://user-images.githubusercontent.com/2924778/37206787-62562160-239a-11e8-9b36-566097d175d8.PNG">
<img width="1080" alt="deluge3" src="https://user-images.githubusercontent.com/2924778/37206788-626e5fa0-239a-11e8-8f3c-79623de477ad.PNG">

**Comment by thelamer** [comment]
There are two environment variables which define the user and guid the container runs deluge as IE:
```
-e PUID=<UID> -e PGID=<GID> 
```
You can either full pub the folder you have it bind mounted to (guest access rwx) or set the uid/gid to your synology user for the folder. 

To find your uid and gid login to your synology via ssh and run

```
id
```
