### ISSUE TITLE
Move Completed Downloads in Label Plugin non-functional

### ISSUE THREAD

**Issue by ngodber** [linuxserver/docker-deluge#44]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I've run into an issue where the 'move completed download' functionality for labels doesn't work in a docker container. I'm simply moving the complete download to a sub directory in the /download folder. 

I've checked debug level logs and there is no error or warning. I've checked all the appropriate config files and again, nothing obvious going on. Frankly, deluge behaves as normal in every way, except when a download completes it simply will not move. I have to manually change the directory through the interface (which works). 

I've tried deleting the container and image. Starting from scratch. The problem still occurs. I'm curious if this occurs also on other machines but don't have the facility to test. 

Libreelec

PUID = 100 PGID= 65534

I'd prefer not to share due to sensitive information. Suffice to say though that there are 0 errors or warnings in the logs (even set to debug level). 

No symlinks.

**Comment by zerojay** [comment]
Had a similar issue myself. It seems to ignore the rules for labels though it did work for me for a very short period of time, maybe a single torrent or two. No errors or anything in output to tell me what the issue is either.

**Comment by zerojay** [comment]
Looking at the deluged.log file, it looks like something about the image is forcing the downloads directory to be /download. If it isn't, labels don't work properly. It is nowhere to be found in either my docker-compose file nor in any of the deluge config files so I don't know where it's coming from. Once I switched from /downloads to /download, this started to work for me.

**Comment by thelamer** [comment]
Yes this is covered in the application setup section of the readme, you currently need to set in the interface your download location, by default we show an example command bind mounting /downloads and we run a chown command against that so I recommend using that.
