### ISSUE TITLE
Global upload speed limit is ignored

### ISSUE THREAD

**Issue by T-Grave** [linuxserver/docker-deluge#45]
**Problem**
When setting the global upload speed limit to 40kb/s for example, torrents are still being uploaded at 200-300kb/s completely saturating my network.

**Host OS**: Ubuntu 16.04.4 LTS

Research suggests it's an issue with the libtorrent version inside the container:
https://forum.deluge-torrent.org/viewtopic.php?f=7&t=54939

After trying to set the global bandwidth upload limit multiple times without success, I tried setting a *per torrent* limit. This worked, so I'll be using this as a workaround, but I still felt like I should report the issue :)

Thanks for the great work on these docker images, my entire homelab / mediacenter is powered by you guys!

**Comment by michaelarnauts** [comment]
Make sense, but this image is using `libtorrent-rasterbar-1.1.7-r0`
```
$ apk info -vv | grep torrent
libtorrent-rasterbar-1.1.7-r0 - Feature complete C++ bittorrent implementation
```

This seems to be the latest version, and is above the mentioned 1.1.5 from that topic post.

Nevertheless, I also see this issue. Setting a global speed limit doesn't work, a per-torrent limit is working fine.

**Comment by bumjrah** [comment]
Is this ever gonna get fixed? Pushes are still being made but this bug still open...

**Comment by bumjrah** [comment]
Okay. So after installing ITConfig plugin & apply, this bug gone.

**Comment by sparklyballs** [comment]
closing this as the problem was originally not of our making and was due to alpine linux changing the version of libtorrent that deluge pulled.

also there appears to be a workaround.

**Comment by FnTm** [comment]
Still seeing this same issue with 144 build, and having to install a plugin to bring back default functionality doesn't seem like a proper fix. @sparklyballs any chance of revisiting this?

**Comment by Suddow** [comment]
What setting in ITconfig is supposed to fix this?  I've had to revert to release/image 110 in order for the bandwidth limit to work, even though I have itconfig.

**Comment by evertonstz** [comment]
Bug persists.

**Comment by thelamer** [comment]
@evertonstz since this issue was filed we have rebased the image to Ubuntu and use the official Deluge PPA. 
If this bug persists, please report it upstream.
