### ISSUE TITLE
Default directory in image is wrong

### ISSUE THREAD

**Issue by serenewaffles** [linuxserver/docker-deluge#47]
The instructions in the README file say to do the following:
`-v </path/to/your/downloads>:/downloads`

The actual default download path is:
`/root/Downloads`

On top of the directory being wrong, it uses a capital "D", which can cause issues on case-sensitive systems (such as Linux).

**Comment by j0nnymoe** [comment]
The README file already mentions this: https://github.com/linuxserver/docker-deluge#setting-up-the-application

**Comment by zerojay** [comment]
It appears to be incorrect still. I had to change the directory to /download instead of /downloads before things started to work properly.

**Comment by j0nnymoe** [comment]
It's not incorrect. We mention in our readme for this container that you need to manually change the directory in deluge to /downloads

**Comment by zerojay** [comment]
Yes, which I did. It reported errors saying it couldn't find /download when doing so even though everything was set to /downloads. Even a full grep through the image to find where it was set to /download found nothing. It only started to work when I started to use /download.
