### ISSUE TITLE
Default UMASK doesn't function properly

### ISSUE THREAD

**Issue by serenewaffles** [linuxserver/docker-deluge#48]
When using the default UMASK (022), I get the following permissions when files are created by the container:
`User: ---`
`Group: -w-`
`Other: -w-`

Setting `-e UMASK_SET=644` fixes this issue.

**Comment by sparklyballs** [comment]
and so you have found what works in your environment and that's why the variable is there.

not particularly seeing a problem here.

**Comment by serenewaffles** [comment]
Upon restarting the container, my configs and files are reset to having the wrong permission. Setting the environment variable does not actually fix the issue.

Further, the default of `022` should not cause the state I am seeing.

**Comment by serenewaffles** [comment]
![image](https://user-images.githubusercontent.com/775693/43919525-336cd5e8-9be4-11e8-95ff-6847db8b723c.png)

The container is unable to do anything to this require configuration file. I can chmod the file to fix the permissions, but the container resets them so that it can't read or write to the file.

**Comment by sparklyballs** [comment]
works fine here on my instance of deluge

could be host related with inherited permissions in the folder tree, selinux etc.

**Comment by serenewaffles** [comment]
I enter the container with the umask set via environment variable.
I then enter the container via `docker exect -it deluge /bin/bash`
I then execute `umask` and get the following result
![image](https://user-images.githubusercontent.com/775693/43919848-49e183a4-9be5-11e8-943c-9a29134011a0.png)

**Comment by serenewaffles** [comment]
My run command:
![image](https://user-images.githubusercontent.com/775693/43920041-d7f7ec50-9be5-11e8-812b-14ad3575f27f.png)

contents of my env file:
![image](https://user-images.githubusercontent.com/775693/43920076-eb3f5550-9be5-11e8-9613-fbd89c9cbd5f.png)

**Comment by sparklyballs** [comment]
it sets the umask for the process itself not the root (or any other) user

example , mine is set to 000 to suit my tastes and host


abc@Unraid-Nas:/proc/216$ grep '^Umask:' "/proc/216/status"
Umask:	0000


216 being the relevant process

**Comment by sparklyballs** [comment]
umask is not set the same as chmod 

![screen shot 2018-08-09 at 20 34 06](https://user-images.githubusercontent.com/4343808/43921413-9d396ee4-9c13-11e8-845a-7ff075a7e665.png)


i personally would set the umask to 000 and see what happens and then refine as per the chart
