### ISSUE TITLE
linuxserver/deluge latest broke webui

### ISSUE THREAD

**Issue by v1ru535** [linuxserver/docker-deluge#67]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Hi all,
I've pull the docker linuxserver/deluge:latest (2019-06-09) and now the web access no longer works:
```
web.Server Traceback (most recent call last):
builtins.TypeError: must be str, not bytes
/usr/lib/python3/dist-packages/twisted/web/server.py:190 in process
189        try:
190            resrc = self.site.getResourceFor(self)
191            if resource._IEncodingResource.providedBy(resrc):
/usr/lib/python3/dist-packages/twisted/web/server.py:826 in getResourceFor
825        request.sitepath = copy.copy(request.prepath)
826        return resource.getChildForRequest(self.resource, request)
827
/usr/lib/python3/dist-packages/twisted/web/resource.py:98 in getChildForRequest
97        request.prepath.append(pathElement)
98        resource = resource.getChildWithDefault(pathElement, request)
99    return resource
/usr/lib/python3/dist-packages/deluge/ui/web/server.py:580 in getChildWithDefault
579        if base[0] != '/':
580            base = '/' + base
581
builtins.TypeError: must be str, not bytes
```
So I went back to the previous version: 
```
docker inspect -f '{{ index .Config.Labels "build_version" }}' deluge
Linuxserver.io version:- 5b398f77-ls22 Build-date:- 2019-06-06T15:03:31-04:00
```
And everything started all over again, am I the only one in this case?

Thanks team.

**Comment by thelamer** [comment]
https://github.com/linuxserver/docker-deluge/issues/66

**Comment by downtowns** [comment]
This does not appear to have been addressed with the update to deluge/ui/web/server.py included in Linuxserver.io version:- 2.0.2-0201906082034ubuntu18.04.1-ls24 Build-date:- 2019-06-11T16:00:06+00:00.  Still receiving the same error with base and nginx reverse proxy configured per https://dev.deluge-torrent.org/wiki/UserGuide/WebUI/ReverseProxy

**Comment by thelamer** [comment]
I linked to the upstream pr and it is now merged and slated for 2.0.3 wip release . Pleases track their repo for progress , we have no control over this.

**Comment by sparklyballs** [comment]
the merge upstream hasn't made it to a release in the ppa as of typing this.

merge 3 hours ago

latest build ppa 7 hours ago

**Comment by sparklyballs** [comment]
https://github.com/deluge-torrent/deluge/pull/244#issuecomment-500986759

https://launchpad.net/~deluge-team/+archive/ubuntu/stable
