### ISSUE TITLE
ERROR: your client is not on the whitelist

### ISSUE THREAD

**Issue by fad6b5f049** [linuxserver/docker-deluge#68]
Noticed due to 0 of my torrents working and trackers are saying "Error: Your client is not on the whitelist". This is on multiple trackers - and the torrents were all working before container update (I usually update on a weekly basis).

I can see that the following information is set to "version" when trying to connect in the web-console, which I am assuming might be connected since a normal install of deluge will show the usual deluge version (as an example, 1.3.15).

https://imgur.com/yNJv2eB

Host OS: Debian
Run:
```
docker run -d --name=deluge \
--restart=unless-stopped \
--net=container:openvpn-client \
-v /dockers/linuxserver/deluge/:/config \
-e PUID=1000 \
-e PGID=1000 \
-e UMASK_SET=002 \
-e TZ=Europe/Paris \
-v /data/downloads/done:/data/downloads/done \
-v /data/downloads/incomplete:/data/downloads/incomplete \
-v /data/media:/data/media \
linuxserver/deluge
```

**Comment by fad6b5f049** [comment]
btw - going to the following version fixes the "deluge version":
linuxserver/deluge:78da80ca-ls20

**Comment by CHBMB** [comment]
@fad6b5f049 
> I can see that the following information is set to "version" when trying to connect in the web-console, which I am assuming might be connected since a normal install of deluge will show the usual deluge version (as an example, 1.3.15).

What's the following information?

**Comment by fad6b5f049** [comment]
> 
> 
> @fad6b5f049
> 
> > I can see that the following information is set to "version" when trying to connect in the web-console, which I am assuming might be connected since a normal install of deluge will show the usual deluge version (as an example, 1.3.15).
> 
> What's the following information?

For some reason my browser wont let me the image here - but here's an imgur link. Thought I included it in the OP, but I guess it slipped through.

https://imgur.com/yNJv2eB

**Comment by sparklyballs** [comment]
the new version of deluge shows that instead of the old style with the version number in. 

the whitelist thing may be due to some trackers not yet set up for the new version. 

in the meantime you can roll back to 1.3.15 by pulling linuxserver/deluge:5b398f77-ls22
and getting on to the tracker that a new version of deluge (2.0.3) is out...
