### ISSUE TITLE
Images not starting up after recent update

### ISSUE THREAD

**Issue by jonatronnn** [linuxserver/docker-deluge#70]
I recently updated my images and have now been getting the following error when starting up my Deluge container, any ideas as to what may be causing this or what I can do to resolve it?

OpenMediaVault (Debain 9)

`sudo docker run -d --name=deluge --net=container:openvpn -e PUID=1001 -e PGID=1000 -e TZ=Europe/London -e UMASK_SET=022 -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/downloads:/downloads  -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/completed:/completed -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/autoadd:/autoadd -v /home/docker/.config/deluge:/config -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/completed-sonarr:/sonarr -v /srv/d1b79442-25b9-4eef-b971-2b1eee560615/downloads/deluge/completed-radarr:/radarr linuxserver/deluge:latest`

> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1001
> User gid:    1000
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing...
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] 99-custom-scripts: executing...
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-scripts: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 23:56:22 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'

**Comment by jonatronnn** [comment]
Okay it seems like they are running, but I can't connect through the thin client any more, webui is working however.

Another major issue I have is that Deluge 2.0 hasn't been whitelisted on my main trackers, is there any way I can roll back to a previous version of the docker image?

**Comment by CHBMB** [comment]
Use a tagged image

https://hub.docker.com/r/linuxserver/deluge/tags

**Comment by jonatronnn** [comment]
> 
> 
> Use a tagged image
> 
> https://hub.docker.com/r/linuxserver/deluge/tags

Thanks for that, will give it a go.

Have just realised perhaps the reason my thinclient can't connect is due to it not being a 2.0 version like the docker image.

**Comment by jonatronnn** [comment]
Issues were due to Deluge being updated to 2.0 in this release and current version thin client being unable to connect to newer versions (no thin client update available yet).

I've rolled back to linuxserver/deluge:5b398f77-ls22 which is the last 1.3.15 update, however as I had already attempted to run the 2.0 deluge container I had to restore my previous torrent state, you can find a backup of this in you ./archive directory of the container's config folder, replace the torrents.fastresume, torrents.fastresume.bak, torrents.state and torrents.state.bak in the ./config/state folder whilst the container is not running and you should be back where you need to be.

It may take a while for trackers to whitelist Deluge 2.0 so you might want to hold off on updating for a while.
