### ISSUE TITLE
twisted.python.failure.Failure OpenSSL.SSL.Error if add URL

### ISSUE THREAD

**Issue by samatkiss** [linuxserver/docker-deluge#71]
I can add the torrent file (but i dont see anywhere on the filesystem), or add the URL but the content behind the torrent file (files folders) arent visible so I cant finish the adding torrent procedure (The ADD button doesnt work the Files and Option tab are grayed out)
In case of adding a torrent file, there arent any error or warning
In case of adding torrent URL, the error is below:

Provide a general summary of the issue in the Title above

Ubuntu 18.04

Docker log output, docker log <container-name>
 [WARNING ][deluge.httpdownloader      :315 ] Error occurred downloading file from "https://URL": [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
21:14:08 [ERROR   ][deluge.ui.web.json_api     :675 ] Failed to add torrent from url https://URL
21:14:08 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'twisted.web._newclient.ResponseNeverReceived'>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]

docker-compose file
The network is bridge mode (custom network)
version: "2"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    hostname: xxxx.xxxxx.xxxx.xx
    network_mode: dmznet1
    dns:
      - xxx.xxx.xxx.xxx
    ports:
      - 8112:8112/tcp
    environment:
      - PUID=1003
      - PGID=1002
      - UMASK_SET=022
      - TZ=Europe/Budapest
    volumes:
      - /ddata/deluge/config:/config
      - /mnt/nfsmedia/plex/data:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.backend=deluge
      - traefik.frontend.rule=Host:xxxx.xxxxx.xxxx.xx
      - traefik.docker.network=dmznet1
      - traefik.port=8112
    restart: unless-stopped

**Comment by j0nnymoe** [comment]
You've not supplied enough information, as per the issue template.
```<!--- If you have an issue with the project, please provide us with the following information -->

<!---  Host OS -->
<!--- Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings. -->
<!--- Docker log output, docker log <container-name>      -->
<!--- Mention if you're using symlinks on any of the volume mounts. -->
```

**Comment by samatkiss** [comment]
Hi!

Is it OK now?

Thanks,
Tamas

**Comment by samatkiss** [comment]
I think, that i`m talking about two problem at the same time but i`m not sure about it.

**Comment by screw** [comment]
I've got the same issue.
When trying to add a torrent via URL through web-ui, the torrent is not downloaded.

docker log deluge:
```
09:31:31 [INFO    ][twisted                    :154 ] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f4557e7bea0>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f4556f1bc18>)
09:31:31 [WARNING ][deluge.httpdownloader      :315 ] Error occurred downloading file from "https://URL": [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
09:31:31 [ERROR   ][deluge.ui.web.json_api     :675 ] Failed to add torrent from url https://<URL>
09:31:31 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'twisted.web._newclient.ResponseNeverReceived'>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
]]

```
Using the recommended docker-compose:
docker-compose.yml:
```
---
version: "2.1"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=127
      - PGID=1002
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=info #optional
    volumes:
      - /var/lib/deluge/.config/deluge:/config
      - /mnt/videos:/mnt/videos
      - /var/media:/var/media
    restart: unless-stopped
```



Torrents added through watch folder works without a problem.
