### ISSUE TITLE
[Feature request] Allow passing interface for deluge-web

### ISSUE THREAD

**Issue by LoveIsGrief** [linuxserver/docker-deluge#74]
deluge-web is started by default on interface 0.0.0.0 which poses a security risk. The option `-i` exists and using an environment variable could be passed to the service in init.d.

The current workaround is to mount a volume which contains a modified [`/etc/services.d/deluge-web/run`] that uses the option.

Thanks for the container!

**Comment by thelamer** [comment]
Can't this be set in the core.conf: 
```
"listen_interface": 
```
??

**Comment by LoveIsGrief** [comment]
the doesn't seem to help nor does the `"interface":` in `web.conf` help since the file keeps getting overwritten when the container is started/restarted.

**Comment by thelamer** [comment]
I think you are referring to the `--ui-interface` setting then not the interface: 
```
Daemon Options:
  -u, --ui-interface <ip-addr>   IP address to listen for UI connections
  -p, --port <port>              Port to listen for UI connections on
  -i, --interface <ip-addr>      IP address to listen for BitTorrent connections
  -o, --outgoing-interface <interface>
                                 The network interface name or IP address for outgoing
                                   BitTorrent connections.
  --read-only-config-keys <comma-separated-keys>
                                 Config keys to be unmodified by `set_config` RPC
```

What does your custom init look like ?

**Comment by LoveIsGrief** [comment]
You are looking at the options of [`deluged`](https://www.systutorials.com/docs/linux/man/1-deluged/), not [`deluge-web`](https://www.systutorials.com/docs/linux/man/1-deluge-web/) :wink: 

```bash
#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
WEB_INTERFACE=${WEB_INTERFACE:-127.0.0.1}

umask "$UMASK_SET"

exec \
        s6-setuidgid abc /usr/bin/deluge-web \
        -i "$WEB_INTERFACE" \
        -d -c /config --loglevel=info
```

**Comment by sparklyballs** [comment]
> You are looking at the options of [`deluged`](https://www.systutorials.com/docs/linux/man/1-deluged/), not [`deluge-web`](https://www.systutorials.com/docs/linux/man/1-deluge-web/) 
> 
> ```shell
> #!/usr/bin/with-contenv bash
> 
> UMASK_SET=${UMASK_SET:-022}
> WEB_INTERFACE=${WEB_INTERFACE:-127.0.0.1}
> 
> umask "$UMASK_SET"
> 
> exec \
>         s6-setuidgid abc /usr/bin/deluge-web \
>         -i "$WEB_INTERFACE" \
>         -d -c /config --loglevel=info
> ```

This breaks the webui by default, 
127.0.0.1 is internal to the container only, doesn't refer to the host.

**Comment by sparklyballs** [comment]
and this can be set in /config/web.conf

```
    "interface": "0.0.0.0",
```

**Comment by LoveIsGrief** [comment]
> This breaks the webui by default, 127.0.0.1 is internal to the container only, doesn't refer to the host.

No, it doesn't. I'm using it right now on my server and forwarding the port through ssh to my computer. The WebUI works. I used the docker command in your README that uses `--network=host`.

> and this can be set in /config/web.conf

I already stated before

>> the doesn't seem to help nor does the `"interface":` in `web.conf` help since the file keeps getting overwritten when the container is started/restarted.

If you don't believe me, try it yourself:

 - use the command you provide in the README to create your container
 - start the container
 - note the interface used `netstat -plant | grep 8112`
 - stop the container
 - modify `web.conf` and close the file
 - restart the container
 - note the result of `grep interface web.conf` 
 - examine the result of `netstat -plant | grep 8112`

If you cannot reproduce or don't consider this issue important, close it. I've made my modifications and they work.

**Comment by sparklyballs** [comment]
web.conf is for the deluge-web

and setting 127.0.0.1 DOES break the webui.

only binding or listening to 127.0.0.1 does not work. localhost/127.0.0.1 is internal to the container and not the host.

**Comment by LoveIsGrief** [comment]
Have you followed the steps I provided?

With the init.d script I provided, this is the result when on my remote host

```
$ netstat -plant | grep 811
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:8112          0.0.0.0:*               LISTEN      30760/deluge-web
```

This is in my `~/.ssh/config`
```
Host remotehost
        HostName 192.168.178.120

        # Share ports
        ## deluge-web
        LocalForward 18112 localhost:8112
```

And this is what I see on my client

![afbeelding](https://user-images.githubusercontent.com/2829538/62533873-030f4800-b848-11e9-80ff-54fb0faae590.png)

If you don't believe me, follow the steps I provided and try it for yourself. If you really don't want to, then just close this. I have my working solution :man_shrugging:

**Comment by sparklyballs** [comment]
i'll go over it one more time... 

if you have that init file , with the default of 127.0.0.1 you cannot access the webui on any remote machine...

WITHOUT

```
[services.d] done.
root@testbed:/# 12:05:52 [WARNING ][deluge.config              :410 ] Unable to open config file /config/web.conf: [Errno 2] No such file or directory: '/config/web.conf'
12:05:52 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
12:05:52 [WARNING ][deluge.config              :410 ] Unable to open config file /config/hostlist.conf: [Errno 2] No such file or directory: '/config/hostlist.conf'
12:05:52 [WARNING ][deluge.config              :475 ] Unable to open config file: /config/hostlist.conf because: [Errno 2] No such file or directory: '/config/hostlist.conf'
12:05:52 [WARNING ][deluge.config              :500 ] Unable to backup old config: [Errno 2] No such file or directory: '/config/hostlist.conf'

root@testbed:/# 12:06:22 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 192.168.1.180)
12:06:31 [WARNING ][deluge.config              :475 ] Unable to open config file: /config/web.conf because: [Errno 2] No such file or directory: '/config/web.conf'
12:06:31 [WARNING ][deluge.config              :500 ] Unable to backup old config: [Errno 2] No such file or directory: '/config/web.conf'
```

can access webui on my remote laptop with the docker running on my server

WITH 

```
root@testbed:/# 12:11:15 [INFO    ][deluge.configmanager:52  ] Setting config directory to: /config
12:11:15 [INFO    ][deluge.ui.ui:70  ] Deluge ui 2.0.3-2-201906121747-ubuntu18.04.1
12:11:15 [INFO    ][deluge.ui.ui:72  ] Starting web ui..
12:11:15 [WARNING ][deluge.config              :410 ] Unable to open config file /config/web.conf: [Errno 2] No such file or directory: '/config/web.conf'
12:11:15 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
12:11:15 [INFO    ][deluge.i18n.util           :102 ] Setting up translations from /usr/lib/python3/dist-packages/deluge/i18n
12:11:15 [WARNING ][deluge.config              :410 ] Unable to open config file /config/hostlist.conf: [Errno 2] No such file or directory: '/config/hostlist.conf'
12:11:15 [WARNING ][deluge.config              :475 ] Unable to open config file: /config/hostlist.conf because: [Errno 2] No such file or directory: '/config/hostlist.conf'
12:11:15 [WARNING ][deluge.config              :500 ] Unable to backup old config: [Errno 2] No such file or directory: '/config/hostlist.conf'
12:11:15 [INFO    ][deluge.ui.web.server       :735 ] Starting webui server at PID 234
12:11:15 [INFO    ][twisted                    :154 ] Site starting on 8112
12:11:15 [INFO    ][twisted                    :154 ] Starting factory <twisted.web.server.Site object at 0x7fc8a7ac7f98>
12:11:15 [INFO    ][deluge.ui.web.server       :750 ] Serving at http://127.0.0.1:8112/
```
no webui access from my remote laptop.
ignore the guff about not finding configs etc, that's just standard stuff for new container.

you can set this in the /config/web.conf which is specific for deluge-web as opposed to core.conf for the daemon.
as is for everyone who accesses their webui remotely, this will instantly break their setup unless they set the variable, and the setting is in an exposed config file , they can set it themselves.
