### ISSUE TITLE
Unable to download to directories outside /downloads

### ISSUE THREAD

**Issue by epicylon** [linuxserver/docker-deluge#77]
HOST OS: OpenMediaVault 4

When I try to download a torrent to a different path than /downloads, the torrent is stuck at 0%. 

I have given Deluge permission to access the other folders I'm trying to download to.

**Comment by aptalca** [comment]
Make sure that those folders on the host are owned by the PUID you're using

**Comment by epicylon** [comment]
That solved it for me.
