### ISSUE TITLE
Auto remove plus  don't work

### ISSUE THREAD

**Issue by BedoM** [linuxserver/docker-deluge#78]
Hello

What is your procedure for install deluge auto remove plus plugin

thank's you =)

**Comment by j0nnymoe** [comment]
Once it get's updated for deluge 2, it will work. 
Github is only used for Bugs/Issues, use our discord or discourse for general suport.

**Comment by TheMrRandomDude** [comment]
Hello. Sorry for reviving this issue, but I am also having a problem with it. It's indeed updated for Deluge 2 and it still doesn't work.

**Comment by junglebus** [comment]
@TheMrRandomDude 
Download this version https://github.com/omaralvarez/deluge-autoremoveplus/pull/51#issuecomment-505122015
-Then rename the egg file (Replace 3.7 with 3.6)
-Copy to the plugins folder in your config directory
-Restart deluge and it works
