### ISSUE TITLE
Unable to add new torrents via URL due to possible Python 3 issue

### ISSUE THREAD

**Issue by courtarro** [linuxserver/docker-deluge#79]
## Expected Behavior
I am able to add a torrent to the server via WebUI by adding a URL directly.

## Current Behavior
The Chrome console shows `deluge-all.js:17 Uncaught TypeError: Cannot read property 'filename' of undefined` but the likely underlying error is on the server side: `[ERROR   ][deluge.ui.web.json_api     :218 ] Object of type 'bytes' is not JSON serializable`. My hypothesis is that this is related to the Python 3 upgrade inside the container, since Python 3 handles strings differently.

## Steps to Reproduce
1. On the main Deluge WebUI page, click "Add" in the top left
2. Click "(+) Url"
3. Paste this URL into the box: `https://archive.org/download/wikidevi/wikidevi_archive.torrent`
4. Click "Add"
5. Note that nothing visible happens, but the console shows the `filename`-related error and the Docker container log shows the `bytes` error.

## Environment
**OS:** Ubuntu Xenial (16.04)
**CPU architecture:** x86_64
**How docker service was installed:** Docker.com PPA

## Command used to create docker container (run/create/compose/screenshot)
From `docker-compose.yaml`:

```
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    volumes:
      - /data/Downloads/Torrents:/downloads
      - /var/local/deluge:/config
    environment:
      - PUID=119
      - PGID=130
      - TZ=America/New_York
    network_mode: host
    restart: always
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    119
User gid:    130
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
23:30:11 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
23:34:21 [ERROR   ][deluge.ui.web.json_api     :218 ] Object of type 'bytes' is not JSON serializable
```

**Comment by sparklyballs** [comment]
I think it depends on the torrent link as to whether it can be added via url... 

latest version of deluge docker here and adding... via the url method works fine here. 

http://releases.ubuntu.com/19.10/ubuntu-19.10-live-server-amd64.iso.torrent

**Comment by frankhommers** [comment]
I have the same problem.

**Comment by woranhun** [comment]
I have  a similar problem while trying to add torrents via url:
```
 02:59:10 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'twisted.web._newclient.ResponseNeverReceived'>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
```

**Comment by thelamer** [comment]
I cannot replicate this URLs work fine for me.
