### ISSUE TITLE
Deluge not starting anymore after latest update

### ISSUE THREAD

**Issue by FlyGuy94** [linuxserver/docker-deluge#8]
I leaving my log here but I don't know how to get debug logs? 

_ _ _
| |___| (_) ___
| / __| | |/ _ \
| \__ \ | | (_) |
|_|___/ |_|\___/
|_|

Brought to you by linuxserver.io
We do accept donations at:
https://www.linuxserver.io/donations
-------------------------------------
GID/UID
-------------------------------------
User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO ] 19:43:42 configmanager:70 Setting config directory to: /config
[INFO ] 19:43:42 ui:124 Deluge ui 1.3.13
[INFO ] 19:43:42 ui:127 Starting web ui..
[INFO ] 19:43:48 server:650 Starting server in PID 213.
[INFO ] 19:43:48 server:664 serving on 0.0.0.0:8112 view at http://127.0.0.1:8112
[INFO ] 19:44:05 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO ] 19:44:05 client:121 Connected to daemon at 127.0.0.1:58846..

**Comment by sparklyballs** [comment]
need more information, 
what is not starting ? is it the webui you cannot access ?

the log indicates the client has started.

**Comment by FlyGuy94** [comment]
Sorry web-ui starts but I cannon connect to the deamon not with web ui nor the client

**Comment by sparklyballs** [comment]
can you run

`docker exec deluge top`

you're looking for entries similar to these, the pid and ppid  numbers will be different. but want to confirm both services are running.

  217   211 abc      S     139m   1%   2   0% {deluged} /usr/bin/python /usr/bin
  215   212 abc      S     131m   1%   0   0% {deluge-web} /usr/bin/python /usr/

**Comment by FlyGuy94** [comment]
Yes I can confirm they are both running but As you can see from my first log deluge never loads its plugins Normally after it does that I can connect.

**Comment by sparklyballs** [comment]
what plugins do you have enabled ?

**Comment by FlyGuy94** [comment]
labels extractor autoremoveplus scheduler think that is all but I can't check obviously.

**Comment by sparklyballs** [comment]
from what you have there, there doesn't appear to be any missing dependencies.

i added the egg for autoremoveplus to a test pull and i enabled the other plugins (standard included with the app itself).

the egg i pulled for autoremoveplus is
AutoRemovePlus-0.6.1-py2.7.egg

**Comment by FlyGuy94** [comment]
Yes I have thesame one.
I tried restarting force updating it. I'm using unraid 6.2 with docker 1.10.3

**Comment by sparklyballs** [comment]
i'm using it on my unraid 6.2 RC4 , i only have the executor plugin running.

but on my test VM i can load those plugins with no issues.

try rolling back to build 11

by changing the template repository field 

from 

`linuserver/deluge` to `linuxserver/deluge:11`

see if it loads that, disable any plugins and then take out the :11 section and see if it loads.

you will probably end up with some orphan images. i'll tell you how to clear after.

**Comment by FlyGuy94** [comment]
Yes that works unfortunatly removing the :11 just gets thesame result but I'm happy my torrents aren't gone. Thanks I will just use this build for a while and try again in a few months.

**Comment by bbusagroningen** [comment]
Hey, what can I do if "217 211 abc S 139m 1% 2 0% {deluged} /usr/bin/python /usr/bin" is not running, only the web UI?

**Comment by teddybee** [comment]
I have the same issue with the latest image. The deluged and deluge-web is running in the container, but the daemon is offline in the webui.
