### ISSUE TITLE
cant start downloading 

### ISSUE THREAD

**Issue by sheiy** [linuxserver/docker-deluge#81]
15:53:43 [WARNING ][deluge.httpdownloader :315 ] Error occurred downloading file from "http://b'centos.org'/": invalid hostname: b'centos.org'
![image](https://user-images.githubusercontent.com/12210038/72049631-42abf580-32fa-11ea-9311-82ce5f3c5d4d.png)

**Comment by aptalca** [comment]
Fill out the issue template

**Comment by djereg** [comment]
Same error here.

**Comment by babacs** [comment]
same issue here on Docker version 20.10.0

**Comment by brandonscript** [comment]
Yep, still happening. OP should re-open with logs and the issue template.
