### ISSUE TITLE
can't get plugins to work

### ISSUE THREAD

**Issue by neffatomic** [linuxserver/docker-deluge#84]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

didn't see any in the list so I tried uploading through the web interface, and tried putting it in the mapped /config file.  Doing a ls | grep search all the plugins I need are in the container.

## Current Behavior

they are not listed in the web interface. Anyone else experiencing this issue?

## Steps to Reproduce

1. pulled newest container
2. configured per recommended instructions
3. connect via browser localhost:8112
4. go to preferences->plugins

## Environment
**OS:** ubuntu 18.04
**CPU architecture:** x86_64/arm32/arm64   x86_64   
**How docker service was installed:**      apt install docker.io

## Command used to create docker container (run/create/compose/screenshot)

docker create --net=host -e PUID=1000 -e PGID=1000 -e TZ=America/Chicago -e DELUGE_LOGLEVEL=error -v /media/judson/Media/Media/Configs/deluge/:/config -v /media/judson/Media/Media/Downloads/:/_downloads -v /media/judson/Media/Media/TV:/_tv -v /media/judson/Media/Media/Movies/:/_movies -v /media/judson/Media/Media/Music/:/_music --restart unless-stopped linuxserver/deluge

## Docker logs

{"log":"[s6-init] making user provided files available at /var/run/s6/etc...exited 0.\n","stream":"stdout","time":"2020-02-02T01:27:28.664231492Z"}
{"log":"[s6-init] ensuring user provided files have correct perms...exited 0.\n","stream":"stdout","time":"2020-02-02T01:27:28.728149588Z"}
{"log":"[fix-attrs.d] applying ownership \u0026 permissions fixes...\n","stream":"stdout","time":"2020-02-02T01:27:28.729350275Z"}
{"log":"[fix-attrs.d] done.\n","stream":"stdout","time":"2020-02-02T01:27:28.730363322Z"}
{"log":"[cont-init.d] executing container initialization scripts...\n","stream":"stdout","time":"2020-02-02T01:27:28.730908826Z"}
{"log":"[cont-init.d] 01-envfile: executing... \n","stream":"stdout","time":"2020-02-02T01:27:28.731986119Z"}
{"log":"[cont-init.d] 01-envfile: exited 0.\n","stream":"stdout","time":"2020-02-02T01:27:28.74318311Z"}
{"log":"[cont-init.d] 10-adduser: executing... \n","stream":"stdout","time":"2020-02-02T01:27:28.743721483Z"}
{"log":"\n","stream":"stdout","time":"2020-02-02T01:27:28.787594126Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2020-02-02T01:27:28.787651355Z"}
{"log":"          _         ()\n","stream":"stdout","time":"2020-02-02T01:27:28.787666166Z"}
{"log":"         | |  ___   _    __\n","stream":"stdout","time":"2020-02-02T01:27:28.787676759Z"}
{"log":"         | | / __| | |  /  \\ \n","stream":"stdout","time":"2020-02-02T01:27:28.787686721Z"}
{"log":"         | | \\__ \\ | | | () |\n","stream":"stdout","time":"2020-02-02T01:27:28.78769903Z"}
{"log":"         |_| |___/ |_|  \\__/\n","stream":"stdout","time":"2020-02-02T01:27:28.78771613Z"}
{"log":"\n","stream":"stdout","time":"2020-02-02T01:27:28.787730708Z"}
{"log":"\n","stream":"stdout","time":"2020-02-02T01:27:28.787740572Z"}
{"log":"Brought to you by linuxserver.io\n","stream":"stdout","time":"2020-02-02T01:27:28.787750213Z"}
{"log":"We gratefully accept donations at:\n","stream":"stdout","time":"2020-02-02T01:27:28.787760235Z"}
{"log":"https://www.linuxserver.io/donate/\n","stream":"stdout","time":"2020-02-02T01:27:28.787770189Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2020-02-02T01:27:28.787779981Z"}
{"log":"GID/UID\n","stream":"stdout","time":"2020-02-02T01:27:28.78779376Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2020-02-02T01:27:28.787811875Z"}
{"log":"\n","stream":"stdout","time":"2020-02-02T01:27:28.797248166Z"}
{"log":"User uid:    1000\n","stream":"stdout","time":"2020-02-02T01:27:28.797291591Z"}
{"log":"User gid:    1000\n","stream":"stdout","time":"2020-02-02T01:27:28.7973056Z"}
{"log":"-------------------------------------\n","stream":"stdout","time":"2020-02-02T01:27:28.797316593Z"}
{"log":"\n","stream":"stdout","time":"2020-02-02T01:27:28.797327054Z"}
{"log":"[cont-init.d] 10-adduser: exited 0.\n","stream":"stdout","time":"2020-02-02T01:27:28.809909599Z"}
{"log":"[cont-init.d] 30-config: executing... \n","stream":"stdout","time":"2020-02-02T01:27:28.812241806Z"}
{"log":"[cont-init.d] 30-config: exited 0.\n","stream":"stdout","time":"2020-02-02T01:27:28.832178469Z"}
{"log":"[cont-init.d] 99-custom-scripts: executing... \n","stream":"stdout","time":"2020-02-02T01:27:28.83448964Z"}
{"log":"[custom-init] no custom files found exiting...\n","stream":"stdout","time":"2020-02-02T01:27:28.851631502Z"}
{"log":"[cont-init.d] 99-custom-scripts: exited 0.\n","stream":"stdout","time":"2020-02-02T01:27:28.853020914Z"}
{"log":"[cont-init.d] done.\n","stream":"stdout","time":"2020-02-02T01:27:28.855013463Z"}
{"log":"[services.d] starting services\n","stream":"stdout","time":"2020-02-02T01:27:28.857269413Z"}
{"log":"[services.d] done.\n","stream":"stdout","time":"2020-02-02T01:27:28.874151858Z"}

**Comment by DickSwart** [comment]
I have the same issue

**Comment by syyyn** [comment]
I was having this problem till I checked the python version which gave me 3.6 with this image.  The plugin I was using was 3.7.  Not sure if this is the same problem but check your plugin python versions.  What I did to get it working was renamed the plugin egg file.  ex)  SimpleExtractor-1.2-py3.7.egg   -->  SimpleExtractor-1.2-py3.6.egg

**Comment by sylflo** [comment]
I have the same problem, I was using the latest image. I am using an older one `linuxserver/deluge:2.0.3-2201906121747ubuntu18.04.1-ls51` and the issue does not seem to appear for this image.

**Comment by ldexterldesign** [comment]
FYI

I can't say I have this issue

OS: macOS, 10.15.3 (19D76)
CPU architecture: x86_64
How docker service was installed: homebrew?

Regards

**Comment by grolnn** [comment]
> I was having this problem till I checked the python version which gave me 3.6 with this image. The plugin I was using was 3.7. Not sure if this is the same problem but check your plugin python versions. What I did to get it working was renamed the plugin egg file. ex) SimpleExtractor-1.2-py3.7.egg --> SimpleExtractor-1.2-py3.6.egg
> 
> ![Screenshot_103](https://user-images.githubusercontent.com/881717/73924759-03da7280-489b-11ea-8077-9b96f1b0bce3.png)

This worked for me. Thanks!

**Comment by moreje** [comment]
Hello,
I wanted to try Deluge from linuxserver docker... but I need the blocklist option.
I've read that it is part of plugins and included in the base release...
my problem is that the plugins section is completely empty! And I can't find any to add :(
what's the problem?
![Capture d’écran du 2021-04-04 10-59-47](https://user-images.githubusercontent.com/5374164/113503987-9aed9980-9535-11eb-9268-9bf12f675186.png)

**Comment by Tonvengo** [comment]
My plugins sections is empty as well. Any ideas?

**Comment by L00maca** [comment]
I'm having the same issue and even the rest of the WebUI is blank.

**Comment by Tantumonium** [comment]
Just installed "linuxserver/deluge" today... same issue... no plugins listed.

**Comment by mauriceoegerli** [comment]
When you first connect, you have to choose your connection in connection manager, should look like this:
![image](https://user-images.githubusercontent.com/15955392/131222709-7bbd31d0-5403-493b-bfa9-4c0b7b0724fd.png)
