### ISSUE TITLE
WebUI on port 80

### ISSUE THREAD

**Issue by jdcmarques** [linuxserver/docker-deluge#85]
Hi,

I am running this container on my qnap creating it with a docker-compose file.

I can't seem to map the WebUI port to anything else
I've tried
```
ports:
    - 80:8112
```
 And even changing the WebUI port to 80 but it doesn't seem to work with this approach either.

Is there a way to do this?

**Comment by tobbenb** [comment]
Please use our discourse forum or discord for support question.

**Comment by ldexterldesign** [comment]
FYI https://github.com/linuxserver/docker-deluge/issues/86
