### ISSUE TITLE
deluge doesn't remember default password changed

### ISSUE THREAD

**Issue by RezzZ** [linuxserver/docker-deluge#88]
## Expected Behavior
after changing the default password, deluge should not remind me to change the 'default' password.

## Current Behavior
With every loggin I get below popup (even though de default password has been changed):
![image](https://user-images.githubusercontent.com/70499/76684331-6bf34580-660b-11ea-916f-af156e1f5fd0.png)

## Steps to Reproduce
1. change default password
2. logout
3. login

## Environment
**OS:**  Centos8 
**CPU architecture:** arm64      
**How docker service was installed:**      
docker installed via the docker compose code:
```  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=timezone
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /opt/downloaders/deluge:/config
      - /opt/downloaders/downloads:/downloads
    restart: unless-stopped```

**Comment by kvn1351** [comment]
Just change the password in the auth file.

**Comment by Mbarmem** [comment]
> 
> 
> Just change the password in the auth file.

Doesn't works, facing the same issue! Needs to change the password each time the container restarts.  The password changes back to default.

**Comment by poojankhanpara** [comment]
Could you please check if the /config dir is mounted from inside docker or see if there are any files on host /opt/downloaders/deluge

**Comment by z-vap** [comment]
I just pulled this image and I am facing the same issue.

**Comment by BadBambi** [comment]
Currently having the same issue and seems to be related to the permissions within the container.
It is trying to write within the container as the UID however the permission set is as root.
`09:59:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.17.0.4)
10:00:45 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.17.0.4)
10:02:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.17.0.4)
10:03:45 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.17.0.4)
10:05:15 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 172.17.0.4)
10:06:14 [ERROR   ][deluge.config              :489 ] Error writing new config file: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/run/s6/services/deluge-web']`

i think someone highlighted this in a previous comment of /root/Downloads as set as a default.

Gone through the documentation: however this has not been of service as yet to resolve the issue - other than running the entire container permissions as root itself, defeats the permissions objective.

`    docker create \
  --name=deluge \
  --net=host \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e UMASK_SET=022 `#optional` \
  -e DELUGE_LOGLEVEL=error `#optional` \
  -v /opt/Deluge:/config \
  -v /mnt/usb1/downloads:/downloads \
  -e FILE__PASSWORD=/run/secrets/mysecretpassword \
  --restart unless-stopped \
  linuxserver/deluge`

![image](https://user-images.githubusercontent.com/33153697/85682628-c604ac00-b6cc-11ea-8774-32327439da59.png)

**Comment by poojankhanpara** [comment]
Try using -v /mnt/usb1/config:/config that way it will mount a dir from your storage where pi user would have permissions.

**Comment by alxpettit** [comment]
I encountered this issue too. :/

**Comment by alxpettit** [comment]
@poojankhanpara this occurs with such a config mount.

**Comment by j0nnymoe** [comment]
This issue is happening due to the `/config` mount not having the correct permissions.

**Comment by thiagocrepaldi** [comment]
> This issue is happening due to the `/config` mount not having the correct permissions.

Exactly. `chown -Rf root:root /config` fixed for me
