### ISSUE TITLE
Unable to set hostname of deluge container

### ISSUE THREAD

**Issue by oshotton** [linuxserver/docker-deluge#9]
Hi Guys,

I'm able to pass the `-h` parameter to `docker run` to specify the containers hostname with a `lsiobase/alpine` container (which is what I believe this Deluge container is based off of) but the flag has no effect when used with the `linuxserver/deluge` container. Please see the command outputs below (I have added **bold** for extra clarity).

Setting the hostname on a `lsiobase/alpine` container (works):
<pre>
ollie@scrappy-server:~$
ollie@scrappy-server:~$ sudo docker run --name hostname-test -h test-hostname --rm -it lsiobase/alpine /bin/sh
Unable to find image 'lsiobase/alpine:latest' locally
latest: Pulling from lsiobase/alpine
a03be5b52c0f: Already exists
f6b6112e832f: Already exists
11b8b96c8a86: Already exists
5e57b4f45c56: Already exists
Digest: sha256:51aa6589be916d520df7d81b6c2e92898defa1fe9e8a6e57be1423afcb0b1d8b
Status: Downloaded newer image for lsiobase/alpine:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We do accept donations at:
https://www.linuxserver.io/donations
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
<b>root@test-hostname:/$ cat /etc/hostname
test-hostname</b>
root@test-hostname:/$ /bin/sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
ollie@scrappy-server:~$
</pre>

Setting the hostname on a `linuxserver/deluge` container (does not work):
<pre>
ollie@scrappy-server:~$
ollie@scrappy-server:~$ sudo docker run --name deluge --net=host -h deluge -e PUID=155 -e PGID=155 -e TZ=Europe/London -v /home/deluge/downloads:/donwloads -v /home/deluge/config:/config --rm -it linuxserver/deluge sh
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We do accept donations at:
https://www.linuxserver.io/donations
-------------------------------------
GID/UID
-------------------------------------
User uid:    155
User gid:    155
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
root@scrappy-server:/$ [INFO    ] 14:36:29 configmanager:70 Setting config directory to: /config
[INFO    ] 14:36:29 ui:124 Deluge ui 1.3.13
[INFO    ] 14:36:29 ui:127 Starting web ui..
[INFO    ] 14:36:29 server:650 Starting server in PID 208.
[INFO    ] 14:36:29 server:664 serving on 0.0.0.0:8112 view at http://127.0.0.1:8112

<b>root@scrappy-server:/$ cat /etc/hostname
scrappy-server</b>
root@scrappy-server:/$ sh exited 0
[INFO    ] 14:36:47 server:681 Shutting down webserver
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
ollie@scrappy-server:~$
</pre>

Thanks
Ollie

**Comment by tobbenb** [comment]
That is normal when you use net=host. The container network is then the same as the host.

**Comment by oshotton** [comment]
Ahh yes, I forgot to add `--net=host` to the `lsiobase/alpine` container in my test above. Both tests now don't change the hostname.

However, the reason I thought you could specify the hostname even when in `--net=host` mode was due to  [docker run documentation](https://docs.docker.com/engine/reference/run/#/network-host).

> Even in host network mode a container has its own UTS namespace by default. As such --hostname is allowed in host network mode and will only change the hostname inside the container.

Am I missing something here?

**Comment by tobbenb** [comment]
This is depending on the docker version installed I guess. I'm unable to set the hostname in host mode. The below is the response from the docker daemon.

`docker: Error response from daemon: Conflicting options: hostname and the network mode.
See 'docker run --help'.
`

**Comment by oshotton** [comment]
So I looked through the docker change log and saw that this option was enabled in [v1.11.0](https://github.com/docker/docker/blob/master/CHANGELOG.md#runtime-4) by [issue #20177](https://github.com/docker/docker/pull/20177). 

However, I am using v1.12.1:
```
ollie@scrappy-server:~$ sudo docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

I have no error response from the docker daemon (everything seems to run ok) but it just doesn't set the hostname.

**Comment by tobbenb** [comment]
There is nothing we do in the baseimage that should interfere with setting the hostname. This is most likely a docker issue we can't do anything about. Or it might be an alpine issue. 
Have you tried any other containers if they work?

I suggest you try creating an issue on the official docker github and see what they say.

**Comment by oshotton** [comment]
I have tried it with the official Ubuntu docker image and had the same results.

Yeah I realise this is no longer an issue with this container image and not the best place for this issue anymore. Thanks for your help @tobbenb.

**Comment by tobbenb** [comment]
No problem :)
