### ISSUE TITLE
Cannot communicate with Thin Client from windows

### ISSUE THREAD

**Issue by RFBomb** [linuxserver/docker-deluge#90]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I cannot connect from the windows Deluge thin client
I have already tried the 'fix' reported here: https://github.com/linuxserver/docker-deluge/issues/21
that did not work for me. I tried multiple variations of it to no avail. 

------------------------------

## Expected Behavior
Should be able to connect from the thin client after following directions on Deluge website. 

## Current Behavior
Thin client does not see the deluge deamon / cannot connect to it at all. 

## Steps to Reproduce
To create this bug, simply spool up a deluge container and try to connect with the windows thin client. 

## Environment
Docker instance is runing on a Raspberry Pi 4 running OpenMediaVault4. 

**How docker service was installed:**      
Through ssh terminal
- Note that I am using portainer to manage my docker containers. 

## Command used to create docker container (run/create/compose/screenshot)

 deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /sharedfolders/HomeFolders/DockerConfigs/deluge:/config
      - /sharedfolders/TorrentsDownloading:/downloads
      - /sharedfolders/Torrents:/Complete
      - /sharedfolders/PLEX:/plex
    restart: unless-stopped  

## Docker logs

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... 

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

We gratefully accept donations at:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    1000

User gid:    1000

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing... 

[cont-init.d] 30-config: exited 0.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.`

**Comment by kvn1351** [comment]
I'm using the Windows client too. 
Be sure to use the unofficial 2.x client. Not 1.x. 

Also, edit the auth file (in the config folder) with your desired password if you can't authenticate once you see the server.

**Comment by RFBomb** [comment]
Using the 'unofficial' client was the fix. Thank you for that tip. Its a shame that there is no 'official' client. 

Here is the link for anyone in the future reading this: 
https://forum.deluge-torrent.org/viewtopic.php?t=55463
