### ISSUE TITLE
Deluge-docker not working with magnet links

### ISSUE THREAD

**Issue by lanceofwhichwedream** [linuxserver/docker-deluge#95]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Deluge having issues with magnet issues

------------------------------

## Expected Behavior
Magnet files would download information like torrent files do

## Current Behavior
Magnet torrents sit stalled and do not download

## Steps to Reproduce
1. Visit https://ipleak.net/
2. Add magnet file from that site to deluge in docker
3. The file neither downloads nor does the website update with ip information as it should

## Environment
**OS:** Ubuntu/ DSM Synology
**CPU architecture:** x86_64
**How docker service was installed:**      Synology package

## Command used to create docker container (run/create/compose/screenshot)
`version: '2'                                                       
services:                                                          
    deluge:                                                        
        image: linuxserver/deluge                                  
        container_name: deluge                                     
        volumes:                                                   
            - /etc/deluge:/config                           
            - /volume1/Downloads/downloads:/downloads                                
            - /volume1/Downloads/downloading:/incomplete-downloads                   
        network_mode: host                                         
        restart: unless-stopped                                    
        environment:                                               
            - VERSION=latest                                       
            - TZ=America/New_York                                  
            - PUID=1000                                            
            - PGID=1000
`

## Docker logs

`usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
10:57:14 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
10:57:24 [WARNING ][deluge.httpdownloader      :315 ] Error occurred downloading file from "http://b'stackoverflow.tech'/": invalid hostname: b'stackoverflow.tech'
10:57:24 [WARNING ][deluge.httpdownloader      :315 ] Error occurred downloading file from "http://b'empirehost.me'/": invalid hostname: b'empirehost.me'
10:57:24 [WARNING ][deluge.httpdownloader      :315 ] Error occurred downloading file from "http://b'animebytes.tv'/": invalid hostname: b'animebytes.tv'
14:35:30 [WARNING ][deluge.httpdownloader      :315 ] Error occurred downloading file from "http://b'bgp.technology'/": invalid hostname: b'bgp.technology'
20:50:12 [ERROR   ][deluge.ui.web.auth         :256 ] Login failed (ClientIP 10.101.5.12)
20:58:21 [WARNING ][deluge.httpdownloader      :315 ] Error occurred downloading file from "http://b'cbcdn.com'/": invalid hostname: b'cbcdn.com'
20:59:40 [WARNING ][deluge.httpdownloader      :315 ] Error occurred downloading file from "http://b'ipleak.net'/": invalid hostname: b'ipleak.net'
`

**Comment by lanceofwhichwedream** [comment]
I strongly suspect the issue to be due to `20:59:40 [WARNING ][deluge.httpdownloader :315 ] Error occurred downloading file from "http://b'ipleak.net'/": invalid hostname: b'ipleak.net'` however I'm unsure how to solve that error.

**Comment by viggy96** [comment]
I have the same issue here.

**Comment by viggy96** [comment]
@lanceofwhichwedream I disabled the "NAT-PMP" option and got my torrenting working again. I think it was interfering with my VPN proxy somehow. I still get the above errors in the log though, but my torrents work and that's what matters.

**Comment by viggy96** [comment]
Issue persists actually, even after disabling "NAT-PMP".

**Comment by drizuid** [comment]
can you reproduce the issue when NOT using your vpn proxy? If not, it's not something we will support. You may visit us on discord in #other-support for assistance with routing a container through a vpn or proxying through a vpn.

**Comment by babacs** [comment]
same issue here on Docker version 20.10.0. No VPN proxy

**Comment by arsenicks** [comment]
FYI I had the same problem, fixed by stopping container, renaming torrents.state and torrents.fastresume and restarting container..
