### ISSUE TITLE
add pip to install some plug in

### ISSUE THREAD

**Issue by pietrondo** [linuxserver/docker-deluge#99]
Hi, i'm looking to install some plug in (like https://github.com/noam09/deluge-telegramer )
but i need to have pip in the "docker image" for install some dependency of the plug in (python module telegram).
Is possible to integrate, in the next version this feature?

Best regard

**Comment by j0nnymoe** [comment]
I don't think this is something we would add to the container but you're able to add it yourself by following this: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
